/*用户主表*/
DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `USER_SYS_ID` INT NOT NULL COMMENT '' auto_increment,
  `USER_ID` VARCHAR(200) NOT NULL COMMENT '用户名',
  `USER_EMAIL` VARCHAR(200) NOT NULL COMMENT '邮箱',
  `USER_PASSWORD` VARCHAR(100) NOT NULL COMMENT '密码md5加密',
  `VERSION` INT NOT NULL COMMENT '版本',
  `USER_STATUS` INT NULL COMMENT '用户状态',
  `CREATE_TIME` TIMESTAMP NULL COMMENT '创建时间',
  `UPDATE_TIME` TIMESTAMP NULL COMMENT '更新时间',
  `CREATE_OP` VARCHAR(100) NULL COMMENT '创建人',
  `UPDATE_OP` VARCHAR(100) NULL COMMENT '更新人',
  `USER_NAME` VARCHAR(100) NULL COMMENT '用户名称',
  `USER_REMARK` VARCHAR(500) NULL COMMENT '',
   PRIMARY KEY (`USER_SYS_ID`))
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8
COMMENT = 'Users\' information for system login.';


/*角色主表*/
DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE `ROLE` (
  `ROLE_SYS_ID` INT NOT NULL COMMENT '系统Id' auto_increment,
  `ROLE_ID` VARCHAR(100) NULL COMMENT '角色Id',
  `ROLE_NAME` VARCHAR(100) NULL COMMENT '角色名称',
  `ROLE_DESCRIPTION` VARCHAR(300) NULL COMMENT '角色描述',
  `ROLE_STATUS` INT NULL DEFAULT 1 COMMENT '状态',
  `CREATE_TIME` TIMESTAMP NULL COMMENT '创建时间',
  `UPDATE_TIME` TIMESTAMP NULL COMMENT '最近修改时间',
  `CREATE_OP` VARCHAR(100) NULL COMMENT '创建者',
  `UPDATE_OP` VARCHAR(100) NULL COMMENT '修改者',
  `VERSION` INT NOT NULL COMMENT '版本',
  PRIMARY KEY (`ROLE_SYS_ID`))
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;



/*用户角色关系表*/
DROP TABLE IF EXISTS `USER_ROLE`;
CREATE TABLE `USER_ROLE` (
  `USER_ROLE_SYS_ID` INT NOT NULL COMMENT '系统Id' auto_increment,
  `USER_SYS_ID` INT NOT NULL COMMENT 'User Id',
  `ROLE_SYS_ID` INT NOT NULL COMMENT '角色Id',
  `CREATE_TIME` TIMESTAMP NULL COMMENT '创建时间',
  `CREATE_OP` VARCHAR(100) NULL COMMENT '创建人',
  `UPDATE_TIME` TIMESTAMP NULL COMMENT '修改时间',
  `UPDATE_OP` VARCHAR(100) NULL COMMENT '修改人',
  `VERSION` INT NOT NULL COMMENT '版本',
  PRIMARY KEY (`USER_ROLE_SYS_ID`),
  FOREIGN KEY (`USER_SYS_ID`) REFERENCES USER(`USER_SYS_ID`) ON DELETE CASCADE,
  FOREIGN KEY (`ROLE_SYS_ID`) REFERENCES ROLE(`ROLE_SYS_ID`) ON DELETE CASCADE
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*资源表*/
DROP TABLE IF EXISTS `RESOURCE`;
CREATE TABLE `RESOURCE` (
  `RESOURCE_SYS_ID` INT NOT NULL COMMENT '系统Id' auto_increment,
  `RESOURCE_NAME` VARCHAR(100) NOT NULL COMMENT '资源名称',
  `RESOURCE_PATTERN` VARCHAR(200) NOT NULL COMMENT '资源定义',
  `RESOURCE_STATUS` VARCHAR(200) NULL DEFAULT 1 COMMENT '状态',
  `RESOURCE_DESCRIPTION` VARCHAR(300) NULL COMMENT '未用',
  `CREATE_TIME` TIMESTAMP NULL COMMENT '创建时间',
  `UPDATE_TIME` TIMESTAMP NULL COMMENT '最近修改时间',
  `CREATE_OP` VARCHAR(100) NULL COMMENT '创建者',
  `UPDATE_OP` VARCHAR(100) NULL COMMENT '修改者',
  `RESOURCE_TYPE` VARCHAR(100) NULL COMMENT '资源类型',
  `PARENT_RESOURCE_SYS_ID` VARCHAR(100) NULL COMMENT '未用',
  `RESOURCE_CODE` VARCHAR(100) NULL COMMENT '资源编码',
   `VERSION` INT NOT NULL COMMENT '版本',
  PRIMARY KEY (`RESOURCE_SYS_ID`))
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*角色资源管理表*/
DROP TABLE IF EXISTS `ROLE_RESOURCE`;
CREATE TABLE `ROLE_RESOURCE` (
  `ROLE_RESOURCE_SYS_ID` INT NOT NULL COMMENT '主键' auto_increment,
  `ROLE_SYS_ID` INT NOT NULL COMMENT '角色外键',
  `RESOURCE_SYS_ID` INT NOT NULL COMMENT '资源外键',
  `VERSION` INT NOT NULL COMMENT '版本',
  PRIMARY KEY (`ROLE_RESOURCE_SYS_ID`),
  FOREIGN KEY (`ROLE_SYS_ID`) REFERENCES ROLE(`ROLE_SYS_ID`) ON DELETE CASCADE,
  FOREIGN KEY (`RESOURCE_SYS_ID`) REFERENCES RESOURCE(`RESOURCE_SYS_ID`) ON DELETE CASCADE
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*聚石塔订单原始表*/
DROP TABLE IF EXISTS `JST_TRADE`;
CREATE TABLE `JST_TRADE` (
`TRADE_SYS_ID` INT NOT NULL COMMENT '主键' auto_increment,
`TID` VARCHAR(200) NOT NULL COMMENT '交易编号',
`ALIPAY_ID` VARCHAR(200)  NULL COMMENT '',
`ALIPAY_NO` VARCHAR(200)  NULL COMMENT '',
`SELLER_NICK` VARCHAR(200) NULL COMMENT '买家昵称',
`PAYMENT` DOUBLE  NULL COMMENT '实付金额',
`RECEIVER_NAME` VARCHAR(200)  NULL COMMENT '收货人的姓名',
`RECEIVER_STATE` VARCHAR(200)  NULL COMMENT '收货人的所在省份',
`RECEIVER_ADDRESS` VARCHAR(200)  NULL COMMENT '收货人的详细地址',
`RECEIVER_ZIP` VARCHAR(200)  NULL COMMENT '收货人的邮编',
`RECEIVER_MOBILE` VARCHAR(200)  NULL COMMENT '收货人的手机号码',
`RECEIVER_PHONE` VARCHAR(200)  NULL COMMENT '收货人的电话号码',
`RECEIVER_CITY` VARCHAR(200) NULL COMMENT '收货人的所在城市',
`RECEIVER_DISTRICT` VARCHAR(200) NULL COMMENT '收货人的所在地区',
`STATUS` VARCHAR(200) NULL COMMENT '交易状态',
`DISCOUNT_FEE` DOUBLE NULL COMMENT '系统优惠金额',
`TOTAL_FEE` DOUBLE NULL COMMENT '商品金额',
`CREATED` TIMESTAMP NULL COMMENT '交易创建时间',
`PAY_TIME` TIMESTAMP NULL COMMENT '付款时间',
`MODIFIED` TIMESTAMP NULL COMMENT '交易修改时间',
`END_TIME` TIMESTAMP NULL COMMENT '交易结束时间',
`SELLER_MEMO` VARCHAR(1000) NULL COMMENT '卖家备注',
`INVOICE_NAME` VARCHAR(200) NULL COMMENT '发票抬头',
`BUYER_NICK` VARCHAR(200) NULL COMMENT '买家昵称',
`STORE_ID` VARCHAR(100) NOT NULL COMMENT '商店ID',
`point_fee` VARCHAR(200)  NULL COMMENT '',
`SHIPPING_TYPE` VARCHAR(200) NULL COMMENT '创建交易时的物流方式',
PRIMARY KEY (`TRADE_SYS_ID`)
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*聚石塔订单促销原始表*/
DROP TABLE IF EXISTS `JST_PROMOTION_DETAIL`;
CREATE TABLE `JST_PROMOTION_DETAIL` (
  `PROMOTION_DETAIL_ID` INT NOT NULL COMMENT '交易的注定单或子订单号' auto_increment,
  `TRADE_SYS_ID` INT NOT NULL COMMENT '',
  `ID` VARCHAR(200) NOT NULL COMMENT '',
  `PROMOTION_NAME` VARCHAR(100) NULL COMMENT '优惠信息的名称',
  `DISCOUNT_FEE` DOUBLE NULL COMMENT '优惠金额',
  `PROMOTION_DESC` VARCHAR(100) NULL COMMENT '优惠活动的描述',
  `PROMOTION_ID` VARCHAR(100) NULL COMMENT '优惠id',
  PRIMARY KEY (`PROMOTION_DETAIL_ID`),
  FOREIGN KEY (`TRADE_SYS_ID`) REFERENCES JST_TRADE(`TRADE_SYS_ID`) ON DELETE CASCADE
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


/*聚石塔订单子服务订单原始表*/
DROP TABLE IF EXISTS `JST_SERVICE_ORDER`;
CREATE TABLE `JST_SERVICE_ORDER` (
`SERVICE_ORDER_ID` INT NOT NULL COMMENT '' auto_increment,
`TRADE_SYS_ID` INT NOT NULL COMMENT '',
`ITEM_OID` VARCHAR(100) NULL COMMENT '服务所属的交易订单号',
`SERVICE_ID` VARCHAR(100) NULL COMMENT '服务数字id',
`SERVICE_DETAIL_URL` VARCHAR(100) NULL COMMENT '服务详情的URL地址',
`NUM` INT NULL COMMENT '购买数量',
`PRICE` DOUBLE NULL COMMENT '服务价格',
`PAYMENT` DOUBLE NULL COMMENT '子订单实付金额',
`TITLE` VARCHAR(100) NULL COMMENT '商品名称',
`TOTAL_FEE` DOUBLE NULL COMMENT '服务子订单总费用',
`BUYER_NICK` VARCHAR(100) NULL COMMENT '卖家昵称',
`SELLER_NICK` VARCHAR(100) NULL COMMENT '卖家昵称',
`PIC_PATH` VARCHAR(100) NULL COMMENT '服务图片地址',
PRIMARY KEY (`SERVICE_ORDER_ID`),
FOREIGN KEY (`TRADE_SYS_ID`) REFERENCES JST_TRADE(`TRADE_SYS_ID`) ON DELETE CASCADE
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;



/*聚石塔订单商品原始表*/
DROP TABLE IF EXISTS `JST_ORDER`;
CREATE TABLE `JST_ORDER` (
`JST_ORDER_SYS_ID` INT NOT NULL COMMENT '' auto_increment,
`TRADE_SYS_ID` INT NOT NULL COMMENT '',
`ITEM_MEAL_NAME` VARCHAR(50) NULL COMMENT '套餐的值',
`PIC_PATH` VARCHAR(100) NULL COMMENT '商品图片的绝对路径',
`REFUND_STATUS` VARCHAR(100) NULL COMMENT '退款状态',
`OUTER_IID` VARCHAR(100) NULL COMMENT '商家外部编码',
`SNAPSHOT_URL` VARCHAR(100) NULL COMMENT '订单快照URL',
`TIMEOUT_ACTION_TIME` TIMESTAMP NULL COMMENT '订单超时到期时间',
`BUYER_RATE` varchar(50) NULL COMMENT '买家是否已评价',
`SELLER_RATE` varchar(50) NULL COMMENT '卖家是否已评价',
 `CID` VARCHAR(100) NULL COMMENT '卖家类型',
 `SUB_ORDER_TAX_FEE` VARCHAR(100) NULL COMMENT '交易商品对应的类目ID',
 `SUB_ORDER_TAX_RATE` VARCHAR(100) NULL COMMENT '子订单关税税费',
 `OID` VARCHAR(100) NULL COMMENT '子订单编号',
 `STATUS` VARCHAR(100) NULL COMMENT '订单状态',
 `TITLE` VARCHAR(100) NULL COMMENT '商品标题',
 `PRICE` Double NULL COMMENT '商品价格',
 `NUM_IID` VARCHAR(100) NULL COMMENT '商品数字ID',
 `ITEM_MEAL_ID` VARCHAR(100) NULL COMMENT '套餐ID',
 `SKU_ID` VARCHAR(100) NULL COMMENT '商品的最小库存单位Sku的id',
  `NUM` INT NULL COMMENT '购买数量',
 `OUTER_SKU_ID`  VARCHAR(100) NULL COMMENT '外部网店自己定义的Sku编号',
 `ORDER_FROM` VARCHAR(100) NULL COMMENT '子订单来源',
 `TOTAL_FEE` DOUBLE NULL COMMENT '应付金额',
 `PAYMENT` DOUBLE NULL COMMENT '子订单实付金额',
  `DISCOUNT_FEE` DOUBLE NULL COMMENT '子订单级订单优惠金额',
   `ADJUST_FEE` DOUBLE NULL COMMENT '子订单级订单优惠金额',
   `SKU_PROPERTIES_NAME` VARCHAR(100) NULL COMMENT 'SKU的值',
`REFUND_ID` VARCHAR(100) NULL COMMENT '最近退款ID',
`IS_OVERSOLD` varchar(10) NULL COMMENT '是否超卖',
`IS_SERVICE_ORDER` varchar(10) NULL COMMENT '是否是服务订单',
`END_TIME` TIMESTAMP NULL COMMENT '子订单的交易结束时间',
`CONSIGN_TIME` TIMESTAMP NULL COMMENT '订单发货时间',
`SHIPPING_TYPE` VARCHAR(100) NULL COMMENT '子订单的运送方式',
`BIND_OID` VARCHAR(100) NULL COMMENT '捆绑的子订单号',
`LOGISTICS_COMPANY` VARCHAR(100) NULL COMMENT '子订单发货的快递公司名称',
`INVOICE_NO` VARCHAR(100) NULL COMMENT '子订单所在包裹的运单号',
`IS_DAIXIAO` VARCHAR(100) NULL COMMENT '表示订单交易是否含有对应的代销采购单',
`DIVIDE_ORDER_FEE` DOUBLE NULL COMMENT '分摊之后的实付金额',
`PART_MJZ_DISCOUNT` DOUBLE NULL COMMENT '优惠分摊',
`TICKET_OUTER_ID` VARCHAR(100) NULL COMMENT '对应门票有效期的外部id',
`TICKET_EXPDATE_KEY` VARCHAR(100) NULL COMMENT '门票有效期的key',
`STORE_CODE` VARCHAR(100) NULL COMMENT '发货的仓库编码',
`IS_WWW` VARCHAR(100) NULL COMMENT '子订单是否是www订单',
`TMSER_SPU_CODE` VARCHAR(100) NULL COMMENT '支持家装类物流的类型',
`matnr` VARCHAR(100) NULL COMMENT 'sku code',
PRIMARY KEY (`JST_ORDER_SYS_ID`),
FOREIGN KEY (`TRADE_SYS_ID`) REFERENCES JST_TRADE(`TRADE_SYS_ID`) ON DELETE CASCADE
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


/*聚石塔扩展信息原始表*/
DROP TABLE IF EXISTS `JST_TRADE_EXT`;
CREATE TABLE `JST_TRADE_EXT` (
`TRADE_EXT_ID` INT NOT NULL COMMENT '' auto_increment,
`TRADE_SYS_ID` INT NOT NULL COMMENT '',
`BEFORE_ENABLE_FLAG` VARCHAR(50) NULL COMMENT 'enable前扩展标识位',
`BEFORE_CLOSE_FLAG` VARCHAR(50) NULL COMMENT '关闭订单前扩展标识位',
`BEFORE_PAY_FLAG` VARCHAR(50) NULL COMMENT '付款前扩展标识位',
 `BEFORE_SHIP_FLAG` VARCHAR(50) NULL COMMENT '发货前扩展标识位',
`BEFORE_CONFIRM_FLAG` VARCHAR(50) NULL COMMENT '确认收货前扩展标识位',
`BEFORE_RATE_FLAG` VARCHAR(50) NULL COMMENT '评价前扩展标识位',
`BEFORE_REFUND_FLAG` VARCHAR(50) NULL COMMENT '退款前扩展标识位',
`BEFORE_MODIFY_FLAG` VARCHAR(50) NULL COMMENT '修改前扩展标识位',
`THIRD_PARTY_STATUS` VARCHAR(50) NULL COMMENT '第三方状态',
`EXTRA_DATA` VARCHAR(50) NULL COMMENT '第三方个性化数据',
`EXT_ATTRIBUTES` VARCHAR(50) NULL COMMENT 'attributes标记',
PRIMARY KEY (`TRADE_EXT_ID`),
FOREIGN KEY (`TRADE_SYS_ID`) REFERENCES JST_TRADE(`TRADE_SYS_ID`) ON DELETE CASCADE
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*聚石塔物流标签原始表*/
DROP TABLE IF EXISTS `JST_LOGISTICS_TAG`;
CREATE TABLE `JST_LOGISTICS_TAG` (
`LOGISTICS_TAG_ID` INT NOT NULL COMMENT '' auto_increment,
`TRADE_SYS_ID` INT NOT NULL COMMENT '',
`ORDER_ID` varchar(100) NULL COMMENT '物流服务标签',
PRIMARY KEY (`LOGISTICS_TAG_ID`),
FOREIGN KEY (`TRADE_SYS_ID`) REFERENCES JST_TRADE(`TRADE_SYS_ID`) ON DELETE CASCADE
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*聚石塔服务标签原始表*/
DROP TABLE IF EXISTS `JST_LOGISTICS_SERVICE_TAG`;
CREATE TABLE `JST_LOGISTICS_SERVICE_TAG` (
`LOGISTICS_SERVICE_TAG_ID` INT NOT NULL COMMENT '标签id' auto_increment,
`LOGISTICS_TAG_ID` INT NOT NULL COMMENT '',
`SERVICE_TAG` VARCHAR(500) NULL COMMENT '物流服务下的标签属性,多个标签之间有;分隔',
`SERVICE_TYPE` VARCHAR(500) NULL COMMENT '',
PRIMARY KEY (`LOGISTICS_SERVICE_TAG_ID`),
FOREIGN KEY (`LOGISTICS_TAG_ID`) REFERENCES JST_LOGISTICS_TAG(`LOGISTICS_TAG_ID`) ON DELETE CASCADE
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


/*订单临时表*/
DROP TABLE IF EXISTS `TEMP_TRADE`;
CREATE TABLE `TEMP_TRADE` (
`TRADE_SYS_ID` INT NOT NULL COMMENT '主键' auto_increment,
`TID` VARCHAR(200) NOT NULL COMMENT '交易编号',
`SELLER_NICK` VARCHAR(200) NULL COMMENT '买家昵称',
`PAYMENT` DOUBLE  NULL COMMENT '实付金额',
`RECEIVER_NAME` VARCHAR(200)  NULL COMMENT '收货人的姓名',
`RECEIVER_STATE` VARCHAR(200)  NULL COMMENT '收货人的所在省份',
`RECEIVER_ADDRESS` VARCHAR(200)  NULL COMMENT '收货人的详细地址',
`RECEIVER_ZIP` VARCHAR(200)  NULL COMMENT '收货人的邮编',
`RECEIVER_MOBILE` VARCHAR(200)  NULL COMMENT '收货人的手机号码',
-- `RECEIVER_PHONE` VARCHAR(200)  NULL COMMENT '收货人的电话号码',
-- `RECEIVER_TOWN` VARCHAR(200) NULL COMMENT '收货人街道地址',
`RECEIVER_CITY` VARCHAR(200) NULL COMMENT '收货人的所在城市',
`RECEIVER_DISTRICT` VARCHAR(200) NULL COMMENT '收货人的所在地区',
`STATUS` VARCHAR(200) NULL COMMENT '交易状态',
`DISCOUNT_FEE` DOUBLE NULL COMMENT '系统优惠金额',
`TOTAL_FEE` DOUBLE NULL COMMENT '商品金额',
`CREATED` TIMESTAMP NULL COMMENT '交易创建时间',
`PAY_TIME` TIMESTAMP NULL COMMENT '付款时间',
`MODIFIED` TIMESTAMP NULL COMMENT '交易修改时间',
`END_TIME` TIMESTAMP NULL COMMENT '交易结束时间',
-- `BUYER_MESSAGE` VARCHAR(200) NULL COMMENT '买家留言',
-- `BUYER_MEMO` VARCHAR(200) NULL COMMENT '买家备注',
`SELLER_MEMO` VARCHAR(1000) NULL COMMENT '卖家备注',
`INVOICE_NAME` VARCHAR(200) NULL COMMENT '发票抬头',
`BUYER_NICK` VARCHAR(200) NULL COMMENT '买家昵称',
`STORE_ID` VARCHAR(100) NOT NULL COMMENT '商店ID',
`point_fee` VARCHAR(100) NOT NULL COMMENT '积分',
`BATCH_NO` INT NOT NULL COMMENT '同步的批次',
`cpd_code` varchar(100) NOT NULL COMMENT 'cpd code',
PRIMARY KEY (`TRADE_SYS_ID`)
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `temp_trade`
ADD COLUMN `ALIPAY_TIME` varchar(100) NULL COMMENT '支付宝到账时间' AFTER `cpd_code`;

ALTER TABLE `temp_trade`
ADD COLUMN `SHIPPING_TYPE` varchar(100) NULL COMMENT 'virtual,express' AFTER `ALIPAY_TIME`;


/*促销临时表*/
DROP TABLE IF EXISTS `TEMP_PROMOTION_DETAIL`;
CREATE TABLE `TEMP_PROMOTION_DETAIL` (
`PROMOTION_DETAIL_ID` INT NOT NULL COMMENT '交易的主订单或自订单号' auto_increment,
`TRADE_SYS_ID` INT NOT NULL COMMENT '',
`ID` VARCHAR(200) NULL COMMENT '',
`PROMOTION_NAME` VARCHAR(100) NULL COMMENT '优惠信息的名称',
`DISCOUNT_FEE` DOUBLE NULL COMMENT '优惠金额',
-- `GIFT_ITEM_NAME` VARCHAR(200) NULL COMMENT '满就送商品时，所送商品的名称',
-- `GIFT_ITEM_ID` VARCHAR(100) NULL COMMENT '赠品的宝贝id',
-- `GIFT_ITEM_NUM` VARCHAR(100) NULL COMMENT '满就送礼物时，送礼物的数量',
`PROMOTION_DESC` VARCHAR(100) NULL COMMENT '优惠活动的描述',
`PROMOTION_ID` VARCHAR(100) NULL COMMENT '优惠id',
`promotion_type` VARCHAR(100) NULL COMMENT 'itemCoupon,shopbonus,ItemPromotion',
PRIMARY KEY (`PROMOTION_DETAIL_ID`),
FOREIGN KEY (`TRADE_SYS_ID`) REFERENCES TEMP_TRADE(`TRADE_SYS_ID`) ON DELETE CASCADE
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


/*订单商品临时表*/
DROP TABLE IF EXISTS `TEMP_ORDER`;
CREATE TABLE `TEMP_ORDER` (
  `JST_ORDER_SYS_ID` INT NOT NULL COMMENT '' auto_increment,
  `TRADE_SYS_ID` INT NOT NULL COMMENT '',
  `PRICE` DOUBLE NULL COMMENT '商品价格',
--    `SKU_ID` VARCHAR(100) NULL COMMENT '商品的最小库存单位Sku的id,未用',
`NUM` INT NULL COMMENT '购买数量',
-- `OUTER_SKU_ID` VARCHAR(100) NULL COMMENT '外部网店自己定义的Sku编号,未用',
`TOTAL_FEE` DOUBLE NULL COMMENT '应付金额',
`PAYMENT` DOUBLE NULL COMMENT '子订单实付金额',
`DISCOUNT_FEE` DOUBLE NULL COMMENT '子订单级订单优惠金额',
-- `SKU_PROPERTIES_NAME` VARCHAR(100) NULL COMMENT 'SKU的值',
`DIVIDE_ORDER_FEE` DOUBLE NULL COMMENT '分摊之后的实付金额',
`PART_MJZ_DISCOUNT` DOUBLE NULL COMMENT '优惠分摊',
`STORE_CODE` VARCHAR(100) NULL COMMENT '发货的仓库编码',
`matrn` varchar(100) null comment '商品编码',
PRIMARY KEY (`JST_ORDER_SYS_ID`),
FOREIGN KEY (`TRADE_SYS_ID`) REFERENCES TEMP_TRADE(`TRADE_SYS_ID`) ON DELETE CASCADE
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


/*订单历史表*/
DROP TABLE IF EXISTS `TRADE_HISTORY`;
CREATE TABLE `TRADE_HISTORY` (
`TRADE_SYS_ID` INT NOT NULL COMMENT '主键' auto_increment,
`TID` VARCHAR(200) NOT NULL COMMENT '交易编号',
`SELLER_NICK` VARCHAR(200) NULL COMMENT '买家昵称',
`PAYMENT` DOUBLE  NULL COMMENT '实付金额',
`RECEIVER_NAME` VARCHAR(200)  NULL COMMENT '收货人的姓名',
`RECEIVER_STATE` VARCHAR(200)  NULL COMMENT '收货人的所在省份',
`RECEIVER_ADDRESS` VARCHAR(200)  NULL COMMENT '收货人的详细地址',
`RECEIVER_ZIP` VARCHAR(200)  NULL COMMENT '收货人的邮编',
`RECEIVER_MOBILE` VARCHAR(200)  NULL COMMENT '收货人的手机号码',
`RECEIVER_CITY` VARCHAR(200) NULL COMMENT '收货人的所在城市',
`RECEIVER_DISTRICT` VARCHAR(200) NULL COMMENT '收货人的所在地区',
`STATUS` VARCHAR(200) NULL COMMENT '交易状态',
`DISCOUNT_FEE` DOUBLE NULL COMMENT '系统优惠金额',
`TOTAL_FEE` DOUBLE NULL COMMENT '商品金额',
`CREATED` TIMESTAMP NULL COMMENT '交易创建时间',
`PAY_TIME` TIMESTAMP NULL COMMENT '付款时间',
`MODIFIED` TIMESTAMP NULL COMMENT '交易修改时间',
`END_TIME` TIMESTAMP NULL COMMENT '交易结束时间',
`SELLER_MEMO` VARCHAR(1000) NULL COMMENT '卖家备注',
`INVOICE_NAME` VARCHAR(200) NULL COMMENT '发票抬头',
`BUYER_NICK` VARCHAR(200) NULL COMMENT '买家昵称',
`STORE_ID` VARCHAR(100) NOT NULL COMMENT '商店ID',
`point_fee` int NOT NULL COMMENT '积分',
`BATCH_NO` INT NOT NULL COMMENT '同步的批次',
`cpd_code` varchar(100) NOT NULL COMMENT 'cpd code',
   PRIMARY KEY (`TRADE_SYS_ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*订单促销历史表*/
DROP TABLE IF EXISTS `PROMOTION_DETAIL_HISTORY`;
CREATE TABLE `PROMOTION_DETAIL_HISTORY` (
`PROMOTION_DETAIL_ID` INT NOT NULL COMMENT '交易的主订单或自订单号' auto_increment,
`TRADE_SYS_ID` INT NOT NULL COMMENT '',
`ID` VARCHAR(200) NULL COMMENT '',
`PROMOTION_NAME` VARCHAR(100) NULL COMMENT '优惠信息的名称',
`DISCOUNT_FEE` DOUBLE NULL COMMENT '优惠金额',
-- `GIFT_ITEM_NAME` VARCHAR(200) NULL COMMENT '满就送商品时，所送商品的名称',
-- `GIFT_ITEM_ID` VARCHAR(100) NULL COMMENT '赠品的宝贝id',
-- `GIFT_ITEM_NUM` VARCHAR(100) NULL COMMENT '满就送礼物时，送礼物的数量',
`PROMOTION_DESC` VARCHAR(100) NULL COMMENT '优惠活动的描述',
`PROMOTION_ID` VARCHAR(100) NULL COMMENT '优惠id',
`promotion_type` VARCHAR(100) NULL COMMENT 'itemCoupon,shopbonus,ItemPromotion',
PRIMARY KEY (`PROMOTION_DETAIL_ID`),
FOREIGN KEY (`TRADE_SYS_ID`) REFERENCES TRADE_HISTORY(`TRADE_SYS_ID`) ON DELETE CASCADE
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


/*订单商品历史表*/
DROP TABLE IF EXISTS `ORDER_HISTORY`;
CREATE TABLE `ORDER_HISTORY` (
  `JST_ORDER_SYS_ID` INT NOT NULL COMMENT '' auto_increment,
  `TRADE_SYS_ID` INT NOT NULL COMMENT '',
  `PRICE` DOUBLE NULL COMMENT '商品价格',
--    `SKU_ID` VARCHAR(100) NULL COMMENT '商品的最小库存单位Sku的id,未用',
`NUM` INT NULL COMMENT '购买数量',
-- `OUTER_SKU_ID` VARCHAR(100) NULL COMMENT '外部网店自己定义的Sku编号,未用',
`TOTAL_FEE` DOUBLE NULL COMMENT '应付金额',
`PAYMENT` DOUBLE NULL COMMENT '子订单实付金额',
`DISCOUNT_FEE` DOUBLE NULL COMMENT '子订单级订单优惠金额',
-- `SKU_PROPERTIES_NAME` VARCHAR(100) NULL COMMENT 'SKU的值',
`DIVIDE_ORDER_FEE` DOUBLE NULL COMMENT '分摊之后的实付金额',
`PART_MJZ_DISCOUNT` DOUBLE NULL COMMENT '优惠分摊',
`STORE_CODE` VARCHAR(100) NULL COMMENT '发货的仓库编码',
`matrn` varchar(100) null comment '商品编码',
PRIMARY KEY (`JST_ORDER_SYS_ID`),
FOREIGN KEY (`TRADE_SYS_ID`) REFERENCES TRADE_HISTORY(`TRADE_SYS_ID`) ON DELETE CASCADE
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*alipay数据表*/
DROP TABLE IF EXISTS `ALIPAY`;
CREATE TABLE `ALIPAY` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `FINANCIAL_SERIAL_NUM` VARCHAR(100) NULL COMMENT '财务流水号',
  `SERVICE_SERIAL_NUM` VARCHAR(100) NOT NULL COMMENT '业务流水号',
    `ORDER_NUM` VARCHAR(100) NULL COMMENT '商户订单号',
    `GOODS_NAME` VARCHAR(500) NULL COMMENT '商品名称',
    `CREATE_TIME` timestamp NULL COMMENT '发生时间',
    `ACCOUNT` VARCHAR(100) NULL COMMENT '对方账号',
     `IN_FEE` DOUBLE NULL COMMENT '收入金额(+)元',
`OUT_FEE` DOUBLE NULL COMMENT '支出金额(-)元',
`BALANCE` DOUBLE NULL COMMENT '账户余额',
`MODE` VARCHAR(100) NULL COMMENT '交易渠道',
`TYPE` VARCHAR(100) NULL COMMENT '业务类型',
`MEMO` VARCHAR(500) NULL COMMENT '备注',
`TRADE_TYPE` INT NULL COMMENT '反查类型',
`VERSION` INT NULL COMMENT '',
`STORE_ID` VARCHAR(100) NULL COMMENT '商店ID',
PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*cpd上传表*/
DROP TABLE IF EXISTS `UPD_CPD`;
CREATE TABLE `UPD_CPD` (
  `CPD_ID` INT NOT NULL COMMENT '' auto_increment,
  `OFFICE_NAME` VARCHAR(50) NULL COMMENT '收获地址',
  `CODE` VARCHAR(50) NULL COMMENT '省或市编码',
 `VERSION` INT NULL COMMENT '省或市编码',
 `STATUS` VARCHAR(100) NULL COMMENT '省或市编码',
PRIMARY KEY (`CPD_ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


/*发票上传表*/
DROP TABLE IF EXISTS `UPD_INVOICE`;
CREATE TABLE `UPD_INVOICE` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `SORG` VARCHAR(50) NULL COMMENT '',
  `DCHL` VARCHAR(10) NULL COMMENT '',
  `BILLDOC` VARCHAR(20) NULL COMMENT '',
  `ITEM` VARCHAR(200) NULL COMMENT '',
  `CNTY` VARCHAR(200) NULL COMMENT '',
`BILLT` VARCHAR(200) NULL COMMENT '',
`BILLDATE` VARCHAR(200) NULL COMMENT '',
`GITNO` VARCHAR(200) NULL COMMENT '',
`OUTBCR` VARCHAR(200) NULL COMMENT '',
`GITSTA` VARCHAR(200) NULL COMMENT '',
`COLDATE` VARCHAR(200) NULL COMMENT '',
`GIT_TEXT` VARCHAR(200) NULL COMMENT '',
`PO_ARNO` VARCHAR(200) NULL COMMENT '',
`SOFF` VARCHAR(200) NULL COMMENT '',
`DESCRIPT` VARCHAR(200) NULL COMMENT '',
`SOFFSTAT` VARCHAR(200) NULL COMMENT '',
`DESCRIPTION` VARCHAR(200) NULL COMMENT '',
`PAYER` VARCHAR(200) NULL COMMENT '',
`SOLD_TO_PT` VARCHAR(200) NULL COMMENT '',
`NAME1` VARCHAR(200) NULL COMMENT '',
`BILL_TO` VARCHAR(200) NULL COMMENT '',
`PO_NUMBER` VARCHAR(200) NULL COMMENT '',
`PO_DATE` VARCHAR(200) NULL COMMENT '',
`CREATED_ON` VARCHAR(200) NULL COMMENT '',
`TI_ME` VARCHAR(200) NULL COMMENT '',
`PAYT` VARCHAR(200) NULL COMMENT '',
`FIXVALDATE` VARCHAR(200) NULL COMMENT '',
`AVALD` VARCHAR(200) NULL COMMENT '',
`CURR` VARCHAR(200) NULL COMMENT '',
`HEAD_TXT` VARCHAR(200) NULL COMMENT '',
`RIN_TEXT` VARCHAR(200) NULL COMMENT '',
`PROJ_ID` VARCHAR(200) NULL COMMENT '',
`PRIPR` VARCHAR(200) NULL COMMENT '',
`DOCCA` VARCHAR(200) NULL COMMENT '',
`MATERIAL` VARCHAR(200) NULL COMMENT '',
`DESCRY` VARCHAR(200) NULL COMMENT '',
`B_FIELD` VARCHAR(200) NULL COMMENT '',
`SLOC` VARCHAR(200) NULL COMMENT '',
`SA_REP_I` VARCHAR(200) NULL COMMENT '',
`SA_UNIT_I` VARCHAR(200) NULL COMMENT '',
`SA_MAN_I` VARCHAR(200) NULL COMMENT '',
`SA_MAN_2` VARCHAR(200) NULL COMMENT '',
`PLNT` VARCHAR(200) NULL COMMENT '',
`NETWR` VARCHAR(200) NULL COMMENT '',
`TURNOVER` VARCHAR(200) NULL COMMENT '',
`UNIT_PR` VARCHAR(200) NULL COMMENT '',
`CMPRE` VARCHAR(200) NULL COMMENT '',
`BILL_QTY` VARCHAR(200) NULL COMMENT '',
`TAX_AMOUNT` VARCHAR(200) NULL COMMENT '',
`AM_ELIGIBL` VARCHAR(200) NULL COMMENT '',
`COST` VARCHAR(200) NULL COMMENT '',
`ITEM_TXT` VARCHAR(200) NULL COMMENT '',
`KBETR` VARCHAR(200) NULL COMMENT '',
`UNIT` VARCHAR(200) NULL COMMENT '',
`REFDOC` VARCHAR(200) NULL COMMENT '',
`REFITM` VARCHAR(200) NULL COMMENT '',
`SALESDOC` VARCHAR(200) NULL COMMENT '',
`SATY` VARCHAR(200) NULL COMMENT '',
`ORDRS` VARCHAR(200) NULL COMMENT '',
`ITCA` VARCHAR(200) NULL COMMENT '',
`SHIP_TO` VARCHAR(200) NULL COMMENT '',
`NAME2` VARCHAR(200) NULL COMMENT '',
`ACC` VARCHAR(200) NULL COMMENT '',
`O_R` VARCHAR(200) NULL COMMENT '',
`PROFIT_CTR` VARCHAR(200) NULL COMMENT '',
`MPG` VARCHAR(200) NULL COMMENT '',
`BRAND` VARCHAR(200) NULL COMMENT '',
`REFERENCE` VARCHAR(200) NULL COMMENT '',
`CAN` VARCHAR(200) NULL COMMENT '',
`CANC_INV` VARCHAR(200) NULL COMMENT '',
`DOCUMENTNO` VARCHAR(200) NULL COMMENT '',
`GROSS` VARCHAR(200) NULL COMMENT '',
`NET` VARCHAR(200) NULL COMMENT '',
`BONUS_ID` VARCHAR(200) NULL COMMENT '',
`CAMPAIGN` VARCHAR(200) NULL COMMENT '',
`VERSION` INT NOT NULL COMMENT '',
PRIMARY KEY (`ID`)
 )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*sku表*/
DROP TABLE IF EXISTS `SKU`;
CREATE TABLE `SKU` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `BRAND` VARCHAR(20) NULL COMMENT '品牌',
  `CID` VARCHAR(50) NULL COMMENT '品类',
 `MATNR` VARCHAR(50) NULL COMMENT 'SKU编号',
 `TMALL_PRICE` DOUBLE NULL COMMENT '价格',
 `SAPPRICE` DOUBLE NULL COMMENT 'Sap价格',
 `VERSION` INT NULL COMMENT '',
 `STATUS` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


/*gift表*/
DROP TABLE IF EXISTS `GIFT_DATA`;
CREATE TABLE `GIFT_DATA` (
  `SKUID` INT NOT NULL COMMENT '' auto_increment,
  `BRAND` VARCHAR(200) NULL COMMENT '品牌',
  `SKUNO` VARCHAR(200) NULL COMMENT 'SAP物料号',
  `NAME` VARCHAR(200) NULL COMMENT '商品名称',
 `MEMO` VARCHAR(500) NULL COMMENT '客服备注简写',
--  `CID` VARCHAR(200) NULL COMMENT '产品品类',
--  `BRAND` VARCHAR(200) NULL COMMENT '品牌',
 `VERSION` INT NULL COMMENT '',
 `STATUS` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`SKUID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*发货单上传表*/
DROP TABLE IF EXISTS `UPD_DELIVERY`;
CREATE TABLE `UPD_DELIVERY` (
  `DELIVERYID` INT NOT NULL COMMENT '' auto_increment,
  `DELIVERYNO` VARCHAR(200) NULL COMMENT '发货单号',
  `TID` VARCHAR(200) NULL COMMENT '淘宝交易号',
  `CREATE_TIME` timestamp NULL COMMENT '提交时间',
  `BUYER_NICK` VARCHAR(200) NULL COMMENT '买家昵称',
  `SELLER_NICK` VARCHAR(200) NULL COMMENT '卖家昵称',
  `SHIPPER_NICK` VARCHAR(200) NULL COMMENT '发货商昵称',
  `LOGISTIC_COMPANY` VARCHAR(200) NULL COMMENT '物流公司',
  `ORDERID` VARCHAR(200) NULL COMMENT '运单号',
  `ORDER_STAUTS` VARCHAR(200) NULL COMMENT '订单状态',
  `RECEIVER_NAME` VARCHAR(200) NULL COMMENT '收件人姓名',
  `STATE` VARCHAR(200) NULL COMMENT '省',
`CITY` VARCHAR(200) NULL COMMENT '市',
`DISTRICT` VARCHAR(200) NULL COMMENT '区',
`ADDRESS` VARCHAR(200) NULL COMMENT '详细地址',
`ZIP` VARCHAR(50) NULL COMMENT '邮编',
`MOBILE` VARCHAR(50) NULL COMMENT '手机',
`PHONE` VARCHAR(50) NULL COMMENT '电话',
`INVOICE_KIND` VARCHAR(100) NULL COMMENT '发票类型',
`INVOICE_NAME` VARCHAR(100) NULL COMMENT '发票类型',
`INVOICE_FEE` DOUBLE NULL COMMENT '发票金额',
`INVOICE_CONTENT` VARCHAR(200) NULL COMMENT '发票内容',
`STORE` VARCHAR(100) NULL COMMENT '仓库名称',
`STORE_OUT_TIME` timestamp NULL COMMENT '实际出库时间',
`title1` VARCHAR(200) NULL COMMENT '商品1名称',
`price1` DOUBLE NULL COMMENT '商品1价格',
`code1` VARCHAR(200) NULL COMMENT '商品1编码',
`num1` INT NULL COMMENT '商品1数量',
`title2` VARCHAR(200) NULL COMMENT '商品2名称',
`price2` DOUBLE NULL COMMENT '商品2价格',
`code2` VARCHAR(200) NULL COMMENT '商品2编码',
`num2` INT NULL COMMENT '商品2数量',
`title3` VARCHAR(200) NULL COMMENT '商品3名称',
`price3` DOUBLE NULL COMMENT '商品3价格',
`code3` VARCHAR(200) NULL COMMENT '商品3编码',
`title4` VARCHAR(200) NULL COMMENT '商品4名称',
`price4` DOUBLE NULL COMMENT '商品4价格',
`code4` VARCHAR(200) NULL COMMENT '商品4编码',
`num4` INT NULL COMMENT '商品4数量',
`title5` VARCHAR(200) NULL COMMENT '商品5名称',
`price5` DOUBLE NULL COMMENT '商品5价格',
`code5` VARCHAR(200) NULL COMMENT '商品5编码',
`num5` INT NULL COMMENT '商品5数量',
`title6` VARCHAR(200) NULL COMMENT '商品6名称',
`price6` DOUBLE NULL COMMENT '商品6价格',
`code6` VARCHAR(200) NULL COMMENT '商品6编码',
`num6` INT NULL COMMENT '商品6数量',
`title7` VARCHAR(200) NULL COMMENT '商品7名称',
`price7` DOUBLE NULL COMMENT '商品7价格',
`code7` VARCHAR(200) NULL COMMENT '商品7编码',
`num7` INT NULL COMMENT '商品7数量',
`title8` VARCHAR(200) NULL COMMENT '商品8名称',
`price8` DOUBLE NULL COMMENT '商品8价格',
`code8` VARCHAR(200) NULL COMMENT '商品8编码',
`num8` INT NULL COMMENT '商品8数量',
`title9` VARCHAR(200) NULL COMMENT '商品9名称',
`price9` DOUBLE NULL COMMENT '商品9价格',
`code9` VARCHAR(200) NULL COMMENT '商品9编码',
`num9` INT NULL COMMENT '商品9数量',
`title10` VARCHAR(200) NULL COMMENT '商品10名称',
`price10` DOUBLE NULL COMMENT '商品10价格',
`code10` VARCHAR(200) NULL COMMENT '商品10编码',
`num10` INT NULL COMMENT '商品10数量',
`version` INT NULL COMMENT '版本号',
  PRIMARY KEY (`DELIVERYID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

-- /*alipay反查表*/
-- DROP TABLE IF EXISTS `EXP_ALIPAY`;
-- CREATE TABLE `EXP_ALIPAY` (
--   `ID` INT NOT NULL COMMENT '' auto_increment,
--   `ACCOUNT_SERIAL_ID` VARCHAR(200) NULL COMMENT '账务流水号',
--   `ODER_ID` VARCHAR(200) NULL COMMENT '商户订单号',
--   `GOODS_NAME` VARCHAR(100) NULL COMMENT '商品名称',
--   `CREATE_TIME` timestamp NULL COMMENT '发生时间',
--   `ACCOUNT_NAME` VARCHAR(100) NULL COMMENT '对方账号',
--   `IN_FEE` DOUBLE NULL COMMENT '收入金额',
--   `OUT_FEE` DOUBLE NULL COMMENT '支出金额',
--   `BALANCE` DOUBLE NULL COMMENT '账户余额',
--    `CHANNEL` VARCHAR(100) NULL COMMENT '交易渠道',
--     `TYPE` VARCHAR(50) NULL COMMENT '业务类型',
--      `MEMO` VARCHAR(500) NULL COMMENT '备注',
--       `VERSION` INT NULL COMMENT '版本号',
--       `STORE_ID` VARCHAR(100) NULL COMMENT '商店ID',
--   PRIMARY KEY (`ID`)
--   )
-- ENGINE = InnoDB AUTO_INCREMENT=100001
-- DEFAULT CHARACTER SET = utf8;

/*财务导出报表*/
DROP TABLE IF EXISTS `EXP_FINACIAL`;
CREATE TABLE `EXP_FINACIAL` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `VARIANT` VARCHAR(100) NULL COMMENT '',
  `DESCRIPTION` VARCHAR(100) NULL COMMENT '',
  `BLDAT` timestamp NULL COMMENT '',
  `BUDAT` timestamp NULL COMMENT '',
  `BKPF` VARCHAR(20) NULL COMMENT '',
  `MONAT` VARCHAR(20) NULL COMMENT '',
  `BUKRS` VARCHAR(20) NULL COMMENT '',
  `WAERS` VARCHAR(20) NULL COMMENT '',
  `NEWBS` VARCHAR(20) NULL COMMENT '',
  `NEWKO` VARCHAR(50) NULL COMMENT '',
  `WRBTR` DOUBLE NULL COMMENT '',
  `ZUONR` VARCHAR(100) NULL COMMENT '',
  `SGTXT` VARCHAR(100) NULL COMMENT '',
  `NEWBS1` VARCHAR(200) NULL COMMENT '',
  `NEWKO1` VARCHAR(20) NULL COMMENT '',
  `NAME1` VARCHAR(20) NULL COMMENT '',
   `ORT01` VARCHAR(50) NULL COMMENT '',
    `WRBTR1` double NULL COMMENT '',
  `ZUONR1` VARCHAR(100) NULL COMMENT '',
   `SGTXT1` VARCHAR(100) NULL COMMENT '',
  `NEWBS2` VARCHAR(200) NULL COMMENT '',
  `NEWKO2` VARCHAR(20) NULL COMMENT '',
  `WRBTR2` double NULL COMMENT '',
  `ZUONR2` VARCHAR(100) NULL COMMENT '',
  `SGTXT2` VARCHAR(300) NULL COMMENT '',
  `VERSION` INT NULL COMMENT '',
  `STORE_ID` VARCHAR(100) NULL COMMENT '',
   `ORDER_STATUS` VARCHAR(100) NULL COMMENT '',
    `ALIPAY_TIME` timestamp NULL COMMENT '',
`TID` VARCHAR(200) NOT NULL COMMENT '交易编号',
`PRICINGDATE` Timestamp NULL COMMENT '订单创建时间',
`CREATE_TIME` timestamp NULL COMMENT '支付宝到账时间',
  PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*发货单导出表*/
DROP TABLE IF EXISTS `EXP_DELIVERY`;
CREATE TABLE `EXP_DELIVERY` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `ORDER_ID` VARCHAR(200) NULL COMMENT '订单号',
  `EXPRESS_NO` VARCHAR(200) NULL COMMENT '运单号',
  `SUB_ORDER_NO` VARCHAR(200) NULL COMMENT '子单号',
  `RECEIVER_ADDRESS` VARCHAR(200) NULL COMMENT '收方地址',
`RECEIVER_MOBILE` VARCHAR(20) NULL COMMENT '收方联系电话',
`RECEIVER_NAME` VARCHAR(20) NULL COMMENT '收方联系人',
`RECEVIER_COMPANY` VARCHAR(100) NULL COMMENT '收方公司',
`RECEVIER_PHONE` VARCHAR(20) NULL COMMENT '收方手机号码',
`PRINT_COUNT` INT NULL COMMENT '打印次数',
`SEND_CONTENT` VARCHAR(200) NULL COMMENT '托寄物内容',
`SEND_NUM` INT NULL COMMENT '托寄物数量',
`SEND_COMPANY` VARCHAR(200) NULL COMMENT '寄件公司',
`SEND_ADDRESS` VARCHAR(200) NULL COMMENT '寄件联系地址',
`SEND_MOBILE` VARCHAR(200) NULL COMMENT '寄件联系电话',
`SENDER_NAME` VARCHAR(200) NULL COMMENT '寄件联系人',
`SEND_START` VARCHAR(200) NULL COMMENT '原寄地',
`SEND_TO` VARCHAR(200) NULL COMMENT '目的地',
`WEIGHT_FEE` double NULL COMMENT '计费重量',
`WEIGHT_ACTUAL` double NULL COMMENT '实际重量',
`CLOSE_TO_ID` VARCHAR(200) NULL COMMENT '收派员工号',
`SHIP_DATE` timestamp NULL COMMENT '寄件日期',
`MEMO` VARCHAR(500) NULL COMMENT '备注',
`SERVICE_TYPE` VARCHAR(200) NULL COMMENT '业务类型',
`URGENT` VARCHAR(200) NULL COMMENT '是否电商加急',
`PAY_MODE` VARCHAR(200) NULL COMMENT '付款方式',
`RECEIVE_LOAN` VARCHAR(200) NULL COMMENT '是否代收货款',
`LOAN_ID` VARCHAR(200) NULL COMMENT '代收货款卡号',
`LOAN_FEE` double NULL COMMENT '代收金额',
`PERMISSION_ORDER` VARCHAR(200) NULL COMMENT '签单返还单号',
`OTHER_FEE` double NULL COMMENT '其它费用',
`AMOUNT` double NULL COMMENT '件数',
`PROTECT_PRICE` VARCHAR(10) NULL COMMENT '是否保价',
`PROTECT_FEE` double NULL COMMENT '报价金额',
`IS_ASKFOR` VARCHAR(10) NULL COMMENT '是否自取',
`IS_SIGN_RECEIPT` VARCHAR(10) NULL COMMENT '是否签回单',
`IS_SEND_ON_TIME` VARCHAR(10) NULL COMMENT '是否定时派送',
`SEND_DATE` timestamp NULL COMMENT '派送日期',
`SEND_TIME` timestamp NULL COMMENT '派送时段',
`SHIPPIG_FEE` double NULL COMMENT '运费',
`LENGTH` double NULL COMMENT '长',
`WIDTH` double NULL COMMENT '宽',
`HEIGHT` double NULL COMMENT '高',
`EXTEND_FIELD1` VARCHAR(200) NULL COMMENT '扩展字段1',
`EXTEND_FIELD2` VARCHAR(200) NULL COMMENT '扩展字段2',
`EXTEND_FIELD3` VARCHAR(200) NULL COMMENT '扩展字段3',
`SHIP_TIME` timestamp NULL COMMENT '寄件时间',
`RECEIVE_STATE` VARCHAR(200) NULL COMMENT '收件状态',
`USERNAME` VARCHAR(200) NULL COMMENT '用户名',
`CUSTOMER_ID` VARCHAR(200) NULL COMMENT '客户ID',
`INVOICE_TITLE` VARCHAR(200) NULL COMMENT '发票抬头',
`INVOICE_N0` VARCHAR(200) NULL COMMENT '发票号',
`INVOICE_FEE` double NULL COMMENT '开票金额',
`GIFT_SKU` VARCHAR(200) NULL COMMENT '礼品物料号',
`GIFT_NUM` int NULL COMMENT '礼品数量',
`TOTAL` double NULL COMMENT '合计',
`VERSION` int NULL COMMENT '版本',
`STORE_ID` VARCHAR(100) NULL COMMENT '商品ID',
`PRICINGDATE` Timestamp NULL COMMENT '订单创建时间',
`ORDER_STATUS` VARCHAR(100) NULL COMMENT '订单状态',
  PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*订单导出报表*/
DROP TABLE IF EXISTS `EXP_ORDER`;
CREATE TABLE `EXP_ORDER` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `SALESORG` VARCHAR(20) NULL COMMENT '',
  `DISTRCHANNEL` VARCHAR(20) NULL COMMENT '',
`SALESDOCTYPE` VARCHAR(20) NULL COMMENT '',
`CUSTOMER` VARCHAR(200) NULL COMMENT '',
`PO_NUMBER` VARCHAR(200) NULL COMMENT '',
`PODATE` VARCHAR(30) NULL COMMENT '',
`PRICINGDATE` Timestamp NULL COMMENT '',
`PARTNERFUNCTN` VARCHAR(30) NULL COMMENT '',
`SHIP_TO_PARTY` VARCHAR(30) NULL COMMENT '',
`NAME` VARCHAR(200) NULL COMMENT '',
`STREET` VARCHAR(200) NULL COMMENT '',
`CITY` VARCHAR(200) NULL COMMENT '',
`POSTAL_CODE` VARCHAR(200) NULL COMMENT '',
`MATERIAL` VARCHAR(200) NULL COMMENT '',
`QUANTITY` int NULL COMMENT '',
`TMALL_PRICE` VARCHAR(200) NULL COMMENT '',
`CONDITION_AMOUNT` double NULL COMMENT '',
`TMALL_POINTS` VARCHAR(200) NULL COMMENT '',
`POINT_AMOUT` int NULL COMMENT '',
`tmall_coupon` varchar(50) NULL COMMENT '',
`coupon_amount` double NULL COMMENT '',
`POACHIVENO` VARCHAR(200) NULL COMMENT '',
`INTERNALNOTE` VARCHAR(200) NULL COMMENT '',
`BILLINGTEXT` VARCHAR(200) NULL COMMENT '',
`TEXT1` VARCHAR(200) NULL COMMENT '',
`TEXT2` VARCHAR(200) NULL COMMENT '',
`TEXT3` VARCHAR(200) NULL COMMENT '',
`VERSION` int NULL COMMENT '',
`STORE_ID` VARCHAR(100) NULL COMMENT '商店Id',
`trade_status` VARCHAR(100) NULL COMMENT '订单状态',
`tid` VARCHAR(100) NULL COMMENT '订单号',
PRIMARY KEY (`ID`)
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*一级仓二级仓地区表*/
DROP TABLE IF EXISTS `AREA`;
CREATE TABLE `AREA` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `name` VARCHAR(200) NULL COMMENT '名称',
  `oname` VARCHAR(200) NULL COMMENT '订单中对应的名称',
  `code` VARCHAR(100) NULL COMMENT '编码',
 `parent_id` INT NULL COMMENT '父地址ID',
 `need_mark` INT NULL COMMENT '是否是省会',
  PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*操作历史表*/
DROP TABLE IF EXISTS `OPERATION _HISTORY`;
CREATE TABLE `OPERATION_HISTORY` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `file_name` VARCHAR(200) NULL COMMENT '名称',
  `file_type` VARCHAR(100) NULL COMMENT '编码',
  `operate_time` timestamp NULL COMMENT '操作时间',
  `operate_op` VARCHAR(100) NULL COMMENT '操作人',
 `model` VARCHAR(200) NULL COMMENT '业务模块',
  PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*当前操作历史表（控制资源的唯一访问）*/
DROP TABLE IF EXISTS `CURRENT_OPERATION`;
CREATE TABLE `CURRENT_OPERATION` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `model` VARCHAR(200) NULL COMMENT '模块',
  `sub_model` VARCHAR(100) NULL COMMENT '子模块',
  `operate_time` timestamp NULL COMMENT '操作时间',
  `operate_op` VARCHAR(100) NULL COMMENT '操作人',
  PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*优惠券表*/
DROP TABLE IF EXISTS `COUPON`;
CREATE TABLE `COUPON` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `coupon_code` VARCHAR(200) NULL COMMENT '编码',
  `coupon_name` VARCHAR(100) NULL COMMENT '名称',
  `coupon_price` double NULL COMMENT 'coupon金额',
  PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*不同批次表*/
DROP TABLE IF EXISTS `SYNC_BATCH`;
CREATE TABLE `SYNC_BATCH` (
`ID` INT NOT NULL COMMENT '' auto_increment,
`BATCH_NO` int NULL COMMENT '批次号',
`LAST_SYNC_TIME` timestamp NULL COMMENT '上次更新时间',
PRIMARY KEY (`ID`)
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


 /*Job执行表*/

DROP TABLE IF EXISTS `JOB_EXEC`;
CREATE TABLE `JOB_EXEC` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `job_name` VARCHAR(200) NULL COMMENT '批次号',
  `batch_no` INT NULL COMMENT '上次更新时间',
  `status` VARCHAR(100) NULL COMMENT 'PROCESS DONE',
   `num` INT NULL COMMENT '记录error执行错误的次数',
  PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


/*备注解析表*/
DROP TABLE IF EXISTS `TRADE_REMARK`;
CREATE TABLE `TRADE_REMARK` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `tid` varchar(200) NOT NULL COMMENT '',
  `INVOICE_TITLE` VARCHAR(500) NULL COMMENT '发票抬头',
  `RECEIVE_NAME` VARCHAR(100) NULL COMMENT '收件人姓名',
`MOBILE` VARCHAR(100) NULL COMMENT '手机号码',
`PHONE` VARCHAR(100) NULL COMMENT '固定电话',
`RECEIVE_ADDRESS` VARCHAR(500) NULL COMMENT '收获地址',
`RECEIVE_ZIP` VARCHAR(100) NULL COMMENT '邮编',
`quantity` int NULL COMMENT '商品数量',
`ticket_name` VARCHAR(500) NULL COMMENT '增票名称',
`ticket_code` VARCHAR(500) NULL COMMENT '增票税号',
`ticket_address` VARCHAR(500) NULL COMMENT '增票地址电话',
`ticket_account` VARCHAR(500) NULL COMMENT '增票名称',
  PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*备注礼品解析表*/
DROP TABLE IF EXISTS `TRADE_REMARK_PRESENT`;
CREATE TABLE `TRADE_REMARK_PRESENT` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `TRADE_REMARK_sys_id` INT NOT NULL COMMENT '',
  `PRESENT_REASON` VARCHAR(200) NULL COMMENT '赠送原因',
  `PRESENT_NAME` VARCHAR(100) NULL COMMENT '礼品名称',
 `PRESENT_QUANTITY` INT NULL COMMENT '礼品数量',
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`TRADE_REMARK_sys_id`) REFERENCES TRADE_REMARK(`ID`) ON DELETE CASCADE
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

/*交易订单备份表*/
DROP TABLE IF EXISTS `JDP_TRADE`;
CREATE TABLE `JDP_TRADE` (
`ID` int NOT NULL COMMENT 'id' auto_increment,
`TID` VARCHAR(100) NOT NULL COMMENT '交易订单id' ,
`STATUS` VARCHAR(100) NOT NULL COMMENT '交易状态',
`TYPE` VARCHAR(100) NULL COMMENT '交易类型',
`SELLER_NICK` VARCHAR(100) NULL COMMENT '卖家昵称',
`BUYER_NICK` VARCHAR(100) NULL COMMENT '买家昵称',
`CREATED` timestamp NULL COMMENT '交易创建时间',
`MODIFIED` timestamp NULL COMMENT '交易修改时间',
`JDP_CREATED` timestamp NULL COMMENT '数据推送的创建时间',
`JDP_MODIFIED` timestamp NULL COMMENT '数据推送的修改时间',
`JDP_HASHCODE` VARCHAR(300) NULL COMMENT 'Jdp用来做数据校验的字段',
`JDP_RESPONSE` text NULL COMMENT 'API返回的整个JSON字符串',
`batch_no` INT NULL COMMENT '更新批次',
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;
/*邮件表*/
DROP TABLE IF EXISTS `EMAIL`;
CREATE TABLE `EMAIL` (
`ID` int NOT NULL COMMENT 'id' auto_increment,
`EMAIL` varchar(200) not null,
`TOKEN` varchar(200) not null,
`TIME` timestamp not null,
`STATUS` int not null,
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


ALTER TABLE `exp_order`
ADD COLUMN `point_fee_remark` VARCHAR(45) NULL COMMENT '1,0' AFTER `tid`;

ALTER TABLE `exp_order`
ADD COLUMN `coupon_remark` VARCHAR(45) NULL COMMENT '1,0' AFTER `point_fee_remark`;

ALTER TABLE `exp_order`
ADD COLUMN `address_remark` VARCHAR(45) NULL COMMENT '1,0' AFTER `coupon_remark`;

ALTER TABLE `temp_trade`
CHANGE COLUMN `point_fee` `point_fee` DOUBLE NOT NULL COMMENT '积分' ;

ALTER TABLE `trade_history`
CHANGE COLUMN `point_fee` `point_fee` DOUBLE NOT NULL COMMENT '积分' ;

alter table EXP_FINACIAL modify wrbtr2 int null;

**************************************************************************
ALTER TABLE `temp_trade`
ADD COLUMN `ALIPAY_NO` VARCHAR(100) NULL COMMENT '' AFTER `SHIPPING_TYPE`;

ALTER TABLE `exp_order`
ADD COLUMN `ALIPAY_NO` VARCHAR(100) NULL COMMENT '' AFTER `address_remark`;

ALTER TABLE `exp_order`
ADD COLUMN `ALIPAY_NO` VARCHAR(100) NULL COMMENT '' AFTER `address_remark`;

ALTER TABLE `exp_order`
ADD COLUMN `RECEIVER_CITY` VARCHAR(200) NULL COMMENT '收货人的所在城市' AFTER `ALIPAY_NO`;

ALTER TABLE `exp_order`
ADD COLUMN `RECEIVER_STATE` VARCHAR(200) NULL COMMENT '收货人的所在省份' AFTER `RECEIVER_CITY`;

ALTER TABLE `alipay` ADD INDEX index_alipay_1 ( `SERVICE_SERIAL_NUM` );

ALTER TABLE `exp_order` ADD INDEX index_exp_order_1 (`ALIPAY_NO`);

ALTER TABLE `exp_order` ADD INDEX index_exp_order_2 (`tid` );

ALTER TABLE `exp_finacial` ADD COLUMN `INVOICE_TITLE` VARCHAR(200) NULL COMMENT '发票抬头';

ALTER TABLE `exp_finacial`add COLUMN `point_fee` DOUBLE NOT NULL COMMENT '积分' ;
create view view_cpd as
select a.tid,b.code office_name from upd_cpd b,jst_trade a where instr(substring_index(a.receiver_state,' ',2),b.office_name)>0 and a.receiver_city not like '%深圳%'
union
select a.tid,b.code office_name from upd_cpd b,jst_trade a where a.receiver_city like '%深圳%' and b.OFFICE_NAME = '深圳'

/*处理业务数据*/
DROP TABLE IF EXISTS `ALIPAY_TRANS`;
CREATE TABLE `ALIPAY_TRANS` (
`ID` INT NOT NULL COMMENT '' auto_increment,
`FINANCIAL_SERIAL_NUM` VARCHAR(100) NULL COMMENT '财务流水号',
`SERVICE_SERIAL_NUM` VARCHAR(100) NOT NULL COMMENT '业务流水号',
`CREATE_TIME` timestamp NULL COMMENT '发生时间',
`IN_FEE` DOUBLE NULL COMMENT '收入金额(+)元',
PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


ALTER TABLE `exp_delivery`
ADD COLUMN `PRESENT_NAME` varchar(500) NULL COMMENT '赠品名称' AFTER `point_fee`;


ALTER TABLE `exp_delivery`
add COLUMN `point_fee` DOUBLE NOT NULL COMMENT '积分' ;
**************************************************************************
-- DROP TABLE IF EXISTS `SALE_ITEM`;
-- CREATE TABLE `SALE_ITEM` (
-- `SALE_ITEM_SYS_ID` INT NOT NULL COMMENT '' auto_increment,
-- `TID` VARCHAR(100) NOT NULL COMMENT '单号',
-- `STORE_ID` VARCHAR(100) NULL COMMENT '商店',
-- `STATUS` VARCHAR(100) NULL COMMENT '订单状态',
-- `CID` VARCHAR(100) NULL COMMENT '品类',
-- `SKU1` VARCHAR(100) NULL COMMENT '单品sku',
-- `SKUS` VARCHAR(100) NULL COMMENT '组合sku',
-- `CREATE_TIME` timestamp NULL COMMENT '订单创建时间',
-- `PAYMENT` DOUBLE NULL COMMENT '支付金额',
-- `PART_MJZ_DISCOUNT` DOUBLE NULL COMMENT '优惠分摊',
-- `SAP_PRICE` DOUBLE NULL COMMENT 'sap金额',
-- `STORE_CODE` varchar(100) null comment '商店编号',
-- PRIMARY KEY (`SALE_ITEM_SYS_ID`)
-- )
-- ENGINE = InnoDB AUTO_INCREMENT=100001
-- DEFAULT CHARACTER SET = utf8;

ALTER TABLE `exp_order`
ADD COLUMN `count_remark` VARCHAR(200) NULL COMMENT '多行标记' AFTER `RECEIVER_STATE`;

ALTER TABLE `temp_trade`
CHANGE COLUMN `cpd_code` `cpd_code` VARCHAR(100) NULL COMMENT 'cpd code' ;


create view view_order_report as
select eo.SALESORG,eo.DISTRCHANNEL,eo.SALESDOCTYPE,vc.OFFICE_NAME,eo.PO_NUMBER,alipay.create_time CREATE_TIME,eo.PRICINGDATE,
eo.PARTNERFUNCTN,vc.OFFICE_NAME OFFICE_NAME1,eo.NAME,eo.STREET,eo.CITY,eo.POSTAL_CODE,eo.MATERIAL,eo.QUANTITY,eo.TMALL_PRICE,
eo.CONDITION_AMOUNT,eo.TMALL_POINTS,eo.POINT_AMOUT,eo.tmall_coupon TMALL_COUPON,eo.coupon_amount COUPON_AMOUNT,eo.POACHIVENO,
eo.INTERNALNOTE,eo.BILLINGTEXT,eo.TEXT1,eo.TEXT2,eo.TEXT3,eo.STORE_ID,eo.trade_status TRADE_STATUS,eo.tid TID,eo.point_fee_remark POINT_FEE_REMARK,
eo.coupon_remark COUPON_REMARK,eo.address_remark ADDRESS_REMARK,eo.count_remark COUNT_REMARK,alipay.IN_FEE,eo.PAYMENT
from exp_order eo left join view_cpd vc on eo.tid = vc.tid
left join view_alipay_trans alipay on eo.ALIPAY_NO = alipay.SERVICE_SERIAL_NUM

ALTER TABLE `exp_order` ADD COLUMN `PAYMENT` Double NULL COMMENT '支付金额';

ALTER TABLE `trade_history`
CHANGE COLUMN `cpd_code` `cpd_code` VARCHAR(100) NULL COMMENT 'cpd code' ;



DROP TABLE IF EXISTS `STORE`;
CREATE TABLE `STORE` (
  `ID` INT NOT NULL COMMENT '' auto_increment,
  `ORDER_STORE` VARCHAR(200) NULL COMMENT '订单中的仓库',
  `PARENT_STORE` VARCHAR(200) NULL COMMENT '菜鸟物流仓库',
  PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `exp_finacial`
ADD COLUMN `ALIPAY_NO` VARCHAR(100) NULL COMMENT '';

ALTER TABLE `exp_delivery`
ADD COLUMN `alipay_no` VARCHAR(100) NULL COMMENT '';

*************************************************************************
ALTER TABLE `trade_history`
ADD COLUMN `ALIPAY_TIME` varchar(100) NULL COMMENT '支付宝到账时间' AFTER `cpd_code`;

ALTER TABLE `exp_delivery`
ADD COLUMN `BUYER_NICK` VARCHAR(200) NULL COMMENT '买家昵称';

ALTER TABLE `trade_history`
ADD COLUMN `SHIPPING_TYPE` varchar(100) NULL COMMENT 'virtual,express' AFTER `ALIPAY_TIME`;

 ALTER TABLE `trade_history`
ADD COLUMN `ALIPAY_NO` VARCHAR(100) NULL COMMENT '' AFTER `SHIPPING_TYPE`;

-- create view view_trade
-- as
-- select * from temp_trade union all select * from trade_history
--
-- create view view_order
-- as
-- select * from temp_order union all select * from order_history
--
-- create view view_promotion_detail
-- as
-- select * from temp_promotion_detail union all select * from promotion_detail_history


/*聚石塔订单原始扩展表*/
DROP TABLE IF EXISTS `JST_TRADE_EXTEND`;
CREATE TABLE `JST_TRADE_EXTEND` (
`TRADE_EXT_SYS_ID` INT NOT NULL COMMENT '主键' auto_increment,
`TRADE_SYS_ID` INT NOT NULL COMMENT '',
`ALIPAY_POINT` VARCHAR(200)  NULL COMMENT '',
`available_confirm_fee` VARCHAR(200)  NULL COMMENT '',
`buyer_alipay_no` VARCHAR(200)  NULL COMMENT '',
`buyer_area` VARCHAR(200)  NULL COMMENT '',
`buyer_email` VARCHAR(200)  NULL COMMENT '',
`buyer_obtain_point_fee` VARCHAR(200)  NULL COMMENT '',
`cod_fee` VARCHAR(200)  NULL COMMENT '',
`cod_status` VARCHAR(200)  NULL COMMENT '',
`commission_fee` VARCHAR(200)  NULL COMMENT '',
`is_3D` VARCHAR(200)  NULL COMMENT '',
`is_brand_sale` VARCHAR(200)  NULL COMMENT '',
`is_force_wlb` VARCHAR(200)  NULL COMMENT '',
`is_lgtype` VARCHAR(200)  NULL COMMENT '',
`is_part_consign` VARCHAR(200)  NULL COMMENT '',
`is_wt` VARCHAR(200)  NULL COMMENT '',
`pcc_af` VARCHAR(200)  NULL COMMENT '',
`real_point_fee` VARCHAR(200)  NULL COMMENT '',
`received_payment` VARCHAR(200)  NULL COMMENT '',
`seller_alipay_no` VARCHAR(200)  NULL COMMENT '',
`seller_can_rate` VARCHAR(200)  NULL COMMENT '',
`seller_cod_fee` VARCHAR(200)  NULL COMMENT '',
`seller_email` VARCHAR(200)  NULL COMMENT '',
`seller_mobile` VARCHAR(200)  NULL COMMENT '',
`seller_name` VARCHAR(200)  NULL COMMENT '',
`seller_phone` VARCHAR(200)  NULL COMMENT '',
`snapshot_url` VARCHAR(200)  NULL COMMENT '',
`PIC_PATH` VARCHAR(200)  NULL COMMENT '商品图片绝对路径',
`SELLER_RATE` VARCHAR(200)  NULL COMMENT '卖家是否已评价',
`POST_FEE` DOUBLE  NULL COMMENT '邮费',
`CONSIGN_TIME` TIMESTAMP NULL COMMENT '卖家发货时间',
`EST_CON_TIME` varchar(100) NULL COMMENT '商家的预计发货时间',
`INVOICE_KIND` VARCHAR(10) NULL COMMENT '发票类型(1电子发票2纸质发票)',
`RECEIVER_COUNTRY` VARCHAR(200) NULL COMMENT '收货人国籍',
`RECEIVER_TOWN` VARCHAR(200) NULL COMMENT '收货人街道地址',
`ORDER_TAX_FEE` VARCHAR(200) NULL COMMENT '天猫国际官网直供主订单关税税费',
`NUM` INT NULL COMMENT '商品购买数量',
`NUM_IID` VARCHAR(200) NULL COMMENT '商品数字编号',
`TITLE` VARCHAR(200) NULL COMMENT '交易标题',
`TYPE` VARCHAR(200) NULL COMMENT '交易类型列表',
`PRICE` DOUBLE NULL COMMENT '	商品价格',
`HAS_POST_FEE` varchar(50) NULL COMMENT '是否包含邮费',
`BUYER_MESSAGE` VARCHAR(500) NULL COMMENT '买家留言',
`BUYER_MEMO` VARCHAR(500) NULL COMMENT '买家备注',
`BUYER_FLAG` INT NULL COMMENT '买家备注旗帜',
`SELLER_FLAG` VARCHAR(200) NULL COMMENT '卖家备注旗帜',
`INVOICE_TYPE` VARCHAR(200) NULL COMMENT '发票类型',
`CREDIT_CARD_FEE` DOUBLE NULL COMMENT '使用信用卡支付金额数',
`MARK_DESC` VARCHAR(200) NULL COMMENT '',
`BUYER_COD_FEE` DOUBLE NULL COMMENT '卖家手工调整金额',
`ADJUST_FEE` DOUBLE NULL COMMENT '卖家手工调整金额',
`TRADE_FROM` VARCHAR(200) NULL COMMENT '交易内部来源',
`BUYER_RATE` VARCHAR(200) NULL COMMENT '买家是否已评价',
PRIMARY KEY (`TRADE_EXT_SYS_ID`) ,
FOREIGN KEY (`TRADE_SYS_ID`) REFERENCES JST_TRADE(`TRADE_SYS_ID`) ON DELETE CASCADE
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;


ALTER TABLE `temp_trade`
ADD COLUMN `RECEIVER_PHONE` VARCHAR(100) NULL COMMENT '';

ALTER TABLE `current_operation`
ADD COLUMN `sys_id` int NULL COMMENT '';

***********************************************************************************************************************
-- 区域销售报表sql优化20150917
ALTER TABLE area ADD INDEX IDX_PARENT_ID (PARENT_ID);

ALTER TABLE sku ADD INDEX IDX_CID_MATNR (CID,MATNR);

ALTER TABLE store ADD INDEX IDX_ORDER_STORE_PARENT_STORE (ORDER_STORE,PARENT_STORE);

ALTER TABLE jst_trade ADD INDEX IDX_ST_CR_TR (STATUS,CREATED,TRADE_SYS_ID)

ALTER TABLE jst_order ADD INDEX IDX_TR_ST_MA (TRADE_SYS_ID,STORE_CODE,MATNR)

-- 销售结构报表sql优化20150917
ALTER TABLE jst_order ADD INDEX IDX_TRADE_SYS_ID_MATNR (TRADE_SYS_ID,MATNR)


create view view_alipay_trans as
select distinct SERVICE_SERIAL_NUM,IN_FEE,CREATE_TIME from Alipay_trans


alter table current_operation modify sys_id varchar(3000);

ALTER TABLE `temp_order`
ADD COLUMN `REFUND_STATUS` VARCHAR(100) NULL COMMENT '' AFTER `matrn`;

ALTER TABLE `exp_order`
ADD COLUMN `REFUND_STATUS` VARCHAR(100) NULL COMMENT '' AFTER `PAYMENT`;

ALTER TABLE `exp_order`
ADD COLUMN `condition_amount_remark` VARCHAR(45) NULL COMMENT '1,0' AFTER `REFUND_STATUS`;
--*********************************2015-09-29******************************************************************
ALTER TABLE `exp_order`
ADD COLUMN `seller_memo` VARCHAR(1000) NULL COMMENT '商家备注';

ALTER TABLE `exp_order`
ADD COLUMN `invoice_name` VARCHAR(200) NULL COMMENT '发票抬头';

ALTER TABLE `exp_order`
ADD COLUMN `receiver_name` VARCHAR(200) NULL COMMENT '收件人姓名';

ALTER TABLE `exp_order`
ADD COLUMN `item_title` VARCHAR(200) NULL COMMENT '宝贝标题';

ALTER TABLE `exp_order`
ADD COLUMN `item_type` VARCHAR(200) NULL COMMENT '行类型';

ALTER TABLE `exp_order`
ADD COLUMN `order_pay` double NULL COMMENT '订单payment减积分';

ALTER TABLE `exp_order`
ADD COLUMN `order_payment` double NULL COMMENT '订单payment';

ALTER TABLE `exp_order`
ADD COLUMN `item_payment` double NULL COMMENT '商品payment';

ALTER TABLE `exp_order`
ADD COLUMN `end_time` timestamp NULL COMMENT '支付宝到账时间';

ALTER TABLE `EXP_FINACIAL`
ADD COLUMN `end_time` timestamp NULL COMMENT '支付宝到账时间';

ALTER TABLE `EXP_DELIVERY`
ADD COLUMN `end_time` timestamp NULL COMMENT '支付宝到账时间';

ALTER TABLE `temp_order`
ADD COLUMN `title` VARCHAR(200) NULL COMMENT '商品标题';
--*********************************2015-09-30******************************************************************
ALTER TABLE `temp_trade`
ADD COLUMN `received_payment` double NULL COMMENT '支付宝到账金额';

ALTER TABLE `exp_order`
ADD COLUMN `received_payment` double NULL COMMENT '支付宝到账金额';

ALTER TABLE `exp_order`
ADD COLUMN `original_point_fee` double NULL COMMENT '订单积分';

ALTER TABLE `exp_order`
ADD COLUMN `original_coupon` double NULL COMMENT '订单优惠券';

ALTER TABLE `EXP_DELIVERY`
ADD COLUMN `seller_memo` VARCHAR(1000) NULL COMMENT '商家备注';

ALTER TABLE `EXP_DELIVERY`
ADD COLUMN `trade_address` VARCHAR(200) NULL COMMENT '	收货人地址';

ALTER TABLE `EXP_DELIVERY`
ADD COLUMN `trade_mobile` VARCHAR(200) NULL COMMENT '	收货人电话';

ALTER TABLE `EXP_DELIVERY`
ADD COLUMN `trade_name` VARCHAR(200) NULL COMMENT '	收货人姓名';

--*********************************2015-10-09******************************************************************

ALTER TABLE `UPD_INVOICE`
ADD COLUMN `LAST_TIME` DATETIME NULL COMMENT '最新更新时间';
--*********************************2015-10-10******************************************************************

ALTER TABLE `jst_trade` ADD INDEX index_alipay_no ( `alipay_no` );

ALTER TABLE `alipay_trans`
ADD COLUMN `tid` VARCHAR(200) NULL COMMENT '订单编号';

--*********************************2015-10-12******************************************************************

ALTER TABLE `EXP_DELIVERY`
ADD COLUMN `alipay_no` VARCHAR(1000) NULL COMMENT '订单alipay流水号';

ALTER TABLE `EXP_DELIVERY`
ADD COLUMN `store_code` VARCHAR(1000) NULL COMMENT '商店code';

DROP TABLE IF EXISTS `TAOBAO_STORE`;
CREATE TABLE `TAOBAO_STORE` (
`ID` INT NOT NULL COMMENT '' auto_increment,
`CODE` VARCHAR(100) NULL COMMENT '商店编码',
`NAME` VARCHAR(100) NOT NULL COMMENT '商店名称',
`SNAME` VARCHAR(100) NOT NULL COMMENT '商店名称简称',
`ALIPAY_NO` VARCHAR(100) NULL COMMENT '商店支付宝账号',
PRIMARY KEY (`ID`)
  )
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

--*********************************2015-10-12******************************************************************

use bsh_ops;
DROP TABLE IF EXISTS `REFUND_SYNC_BATCH`;
CREATE TABLE `REFUND_SYNC_BATCH` (
`ID` INT NOT NULL COMMENT '' auto_increment,
`BATCH_NO` int NULL COMMENT '批次号',
`LAST_SYNC_TIME` timestamp NULL COMMENT '上次更新时间',
PRIMARY KEY (`ID`)
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;




DROP TABLE IF EXISTS `JDP_REFUND`;
CREATE TABLE `JDP_REFUND` (
`ID` int NOT NULL COMMENT 'id' auto_increment,
`REFUND_ID` VARCHAR(100) NOT NULL COMMENT '交易退款单id' ,
`OID` VARCHAR(100) NOT NULL COMMENT '交易订单子id' ,
`TID` VARCHAR(100) NOT NULL COMMENT '交易订单id' ,
`STATUS` VARCHAR(100) NOT NULL COMMENT '交易状态',
`SELLER_NICK` VARCHAR(100) NULL COMMENT '卖家昵称',
`BUYER_NICK` VARCHAR(100) NULL COMMENT '买家昵称',
`CREATED` timestamp NULL COMMENT '交易创建时间',
`MODIFIED` timestamp NULL COMMENT '交易修改时间',
`JDP_CREATED` timestamp NULL COMMENT '数据推送的创建时间',
`JDP_MODIFIED` timestamp NULL COMMENT '数据推送的修改时间',
`JDP_HASHCODE` VARCHAR(300) NULL COMMENT 'Jdp用来做数据校验的字段',
`JDP_RESPONSE` text NULL COMMENT 'API返回的整个JSON字符串',
`batch_no` INT NULL COMMENT '更新批次',
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;




DROP TABLE IF EXISTS `TRADE_REFUND`;
CREATE TABLE `TRADE_REFUND` (
`ID` int NOT NULL COMMENT 'id' auto_increment,
`shipping_type` VARCHAR(100) NOT NULL COMMENT '交易退款单id' ,
`cs_status` VARCHAR(10) NOT NULL COMMENT '交易退款单id' ,
`advance_status` VARCHAR(10) NOT NULL COMMENT '交易退款单id' ,
`split_taobao_fee` double NOT NULL COMMENT '分账给淘宝的钱' ,
`split_seller_fee` double NOT NULL COMMENT '分账给卖家的钱' ,
`refund_id` VARCHAR(100) NOT NULL COMMENT '退款单号' ,
`tid` VARCHAR(100) NOT NULL COMMENT '淘宝交易单号' ,
`oid` VARCHAR(100) NOT NULL COMMENT '交易订单子id' ,
`alipay_no` VARCHAR(100) NOT NULL COMMENT '交易订单子id' ,
`total_fee` double NOT NULL COMMENT '交易总金额' ,
`seller_nick` VARCHAR(100) NULL COMMENT '卖家昵称',
`buyer_nick` VARCHAR(100) NULL COMMENT '买家昵称',
`created` timestamp NULL COMMENT '退款申请时间',
`modified` timestamp NULL COMMENT '更新时间',
`order_status` VARCHAR(100) NOT NULL COMMENT '退款对应的订单交易状态',
`status` VARCHAR(100) NOT NULL COMMENT '退款状态',
`good_status` VARCHAR(100) NOT NULL COMMENT '货物状态' ,
`has_good_return` VARCHAR(100) NOT NULL COMMENT '买家是否需要退货' ,
`refund_fee` double NOT NULL COMMENT '退还给买家的金额' ,
`payment` double NOT NULL COMMENT '支付给卖家的金额' ,
`reason` VARCHAR(200) NOT NULL COMMENT '退款原因' ,
`description` VARCHAR(1000) NOT NULL COMMENT '退款说明' ,
`title` VARCHAR(100) NOT NULL COMMENT '商品标题' ,
`price` double NOT NULL COMMENT '商品价格' ,
`num` int NOT NULL COMMENT '商品购买数量' ,
`good_return_time` timestamp NOT NULL COMMENT '退货时间' ,
`company_name` VARCHAR(100) NOT NULL COMMENT '物流公司名称' ,
`sid` VARCHAR(100) NOT NULL COMMENT '退货运单号' ,
`address` VARCHAR(200) NOT NULL COMMENT '卖家收货地址' ,
`num_iid` VARCHAR(100) NOT NULL COMMENT '申请退款的商品数字编号' ,
`refund_phase` VARCHAR(100) NOT NULL COMMENT '退款阶段' ,
`refund_version` VARCHAR(100) NOT NULL COMMENT '退款版本号' ,
`sku` VARCHAR(100) NOT NULL COMMENT '商品SKU信息' ,
`attribute` VARCHAR(1000) NOT NULL COMMENT '退款扩展属性' ,
`outer_id` VARCHAR(100) NOT NULL COMMENT '商品外部商家编码' ,
`operation_contraint` VARCHAR(100) NOT NULL COMMENT '退款约束' ,
`store_id` VARCHAR(100) NOT NULL COMMENT '商店CODE' ,
`record_create` timestamp NULL COMMENT '交易创建时间',
`batch_no` INT NULL COMMENT '更新批次',
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

DROP TABLE IF EXISTS `TRADE_REFUND_ERROR`;
CREATE TABLE `TRADE_REFUND_ERROR` (
`ID` int NOT NULL COMMENT 'id' auto_increment,
`refund_id` VARCHAR(100) NOT NULL COMMENT '退款单号' ,
PRIMARY KEY (`ID`)
)
ENGINE = InnoDB AUTO_INCREMENT=100001
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `EXP_order`
ADD COLUMN `refund_id` VARCHAR(100) NULL COMMENT '退款单号';

ALTER TABLE `temp_order`
ADD COLUMN `refund_id` VARCHAR(100) NULL COMMENT '退款单号';

update temp_order a  inner join (
	select c.refund_id,a.trade_sys_id from temp_trade a,jst_trade b, jst_order c
    where a.tid = b.tid and b.trade_sys_id = c.trade_sys_id
	and c.refund_id != '') d on a.trade_sys_id = d.trade_sys_id set a.refund_id = d.refund_id

update exp_order a  inner join (
	select c.refund_id,a.tid,c.title from temp_trade a,jst_trade b, jst_order c
    where a.tid = b.tid and b.trade_sys_id = c.trade_sys_id
	and c.refund_id != '') d on a.tid = d.tid and d.title = a.item_title set a.refund_id = d.refund_id

ALTER TABLE `exp_delivery`
ADD COLUMN `RECEIVER_STATE` varchar(500) NULL COMMENT '收货人的所在省份';

ALTER TABLE `exp_delivery`
ADD COLUMN `RECEIVER_CITY` varchar(500) NULL COMMENT '收货人的所在城市';

ALTER TABLE `exp_delivery`
ADD COLUMN `RECEIVER_DISTRICT` varchar(500) NULL COMMENT '收货人的所在地区';

update exp_delivery ed inner join temp_trade tt on ed.order_id = tt.tid set ed.RECEIVER_STATE = tt.RECEIVER_STATE,ed.RECEIVER_CITY = tt.RECEIVER_CITY

--更新item积分信息
update exp_order a inner join (select tid,item_type,original_point_fee from exp_order where item_type = 'order') b on a.tid = b.tid set a.original_point_fee = b.original_point_fee;

--双十一预售订单配置表
DROP TABLE IF EXISTS `report_config`;
CREATE TABLE `report_config` (
  `id` INT NOT NULL COMMENT '',
  `report_name` VARCHAR(45) NULL COMMENT '报表名称',
  `report_column` VARCHAR(45) NULL COMMENT '报表列名',
  `taobao_column` VARCHAR(45) NULL COMMENT '对应淘宝列名',
  `order_index` INT NULL COMMENT '获取数据的优先级，1为先',
  `trade_status` VARCHAR(45) NULL COMMENT '订单状态',
  PRIMARY KEY (`id`)
  )
  ENGINE = InnoDB AUTO_INCREMENT=100001
  DEFAULT CHARACTER SET = utf8;

--插入配置表基础数据
INSERT INTO `report_config` (`id`, `report_name`, `report_column`, `taobao_column`, `order_index`, `trade_status`)
VALUES ('1', 'order_report', 'originalCoupon', 'partMjzDiscount', '1', 'step');
INSERT INTO `report_config` (`id`, `report_name`, `report_column`, `taobao_column`, `order_index`, `trade_status`)
VALUES ('2', 'order_report', 'originalCoupon', 'adjustFee', '2', 'step');

--temp trade 表字段补全
ALTER TABLE `temp_trade` ADD COLUMN `ADJUST_FEE` DECIMAL(10,2) NULL COMMENT '卖家手工调整金额';
ALTER TABLE `temp_trade` ADD COLUMN `ALIPAY_ID` varchar(200) NULL COMMENT '买家的支付宝ID号，在UIC中有记录，买家支付宝的唯一标示，不因为买家更换EMAIL账号而改变';
ALTER TABLE `temp_trade` ADD COLUMN `ALIPAY_POINT` INT NULL COMMENT '付款时使用的支付宝积分的额度,单位分，比如返回1，则为1分钱';
ALTER TABLE `temp_trade` ADD COLUMN `AVAILABLE_CONFIRM_FEE` DECIMAL(10,2) NULL COMMENT '交易中剩余的确认收货金额（这个金额会随着子订单确认收货而不断减少，交易成功后会变为零）';
ALTER TABLE `temp_trade` ADD COLUMN `BUYER_ALIPAY_NO` VARCHAR(200) NULL COMMENT '买家支付宝账号';
ALTER TABLE `temp_trade` ADD COLUMN `BUYER_AREA` VARCHAR(200) NULL COMMENT '买家下单的地区';
ALTER TABLE `temp_trade` ADD COLUMN `BUYER_COD_FEE` DECIMAL(10,2) NULL COMMENT '买家货到付款服务费';
ALTER TABLE `temp_trade` ADD COLUMN `BUYER_EMAIL` VARCHAR(200) NULL COMMENT '买家邮件地址';
ALTER TABLE `temp_trade` ADD COLUMN `BUYER_OBTAIN_POINT_FEE` INT NULL COMMENT '买家获得积分,返点的积分';
ALTER TABLE `temp_trade` ADD COLUMN `BUYER_RATE` VARCHAR(10) NULL COMMENT '买家是否已评价可选值:TRUE(已评价),FALSE(未评价)。如买家只评价未打分，此字段仍返回FALSE';
ALTER TABLE `temp_trade` ADD COLUMN `COD_FEE` DECIMAL(10,2) NULL COMMENT '货到付款服务费';
ALTER TABLE `temp_trade` ADD COLUMN `COD_STATUS` VARCHAR(200) NULL COMMENT '货到付款物流状态';
ALTER TABLE `temp_trade` ADD COLUMN `COMMISSION_FEE` DECIMAL(10,2) NULL COMMENT '交易佣金';
ALTER TABLE `temp_trade` ADD COLUMN `CONSIGN_TIME` TIMESTAMP NULL COMMENT '卖家发货时间';
ALTER TABLE `temp_trade` ADD COLUMN `CREDIT_CARD_FEE` DECIMAL(10,2) NULL COMMENT '使用信用卡支付金额数';
ALTER TABLE `temp_trade` ADD COLUMN `HAS_POST_FEE` VARCHAR(10) NULL COMMENT '是否包含邮费，与AVAILABLE_CONFIRM_FEE同时使用';
ALTER TABLE `temp_trade` ADD COLUMN `IS_3D` VARCHAR(10) NULL COMMENT '是否3D交易';
ALTER TABLE `temp_trade` ADD COLUMN `IS_BRAND_SALE` VARCHAR(10) NULL COMMENT '表示是否是品牌特卖';
ALTER TABLE `temp_trade` ADD COLUMN `IS_DAIXIAO` VARCHAR(10) NULL COMMENT '表示订单交易是否含有对应的代销采购单BOOLEAN';
ALTER TABLE `temp_trade` ADD COLUMN `IS_FORCE_WLB` VARCHAR(10) NULL COMMENT '订单是否强制使用物流宝发货，当此字段与IS_BRAND_SALE均为TRUE时，订单强制物流宝发货';
ALTER TABLE `temp_trade` ADD COLUMN `IS_LGTYPE` VARCHAR(10) NULL COMMENT '是否保障速递';
ALTER TABLE `temp_trade` ADD COLUMN `IS_PART_CONSIGN` VARCHAR(10) NULL COMMENT '是否是多次发货的订单如果卖家对订单进行多次发货';
ALTER TABLE `temp_trade` ADD COLUMN `IS_WT` VARCHAR(10) NULL COMMENT '表示订单交易是否网厅订单';
ALTER TABLE `temp_trade` ADD COLUMN `NUM` INT NULL COMMENT '商品购买数量';
ALTER TABLE `temp_trade` ADD COLUMN `NUM_IID` VARCHAR(200) NULL COMMENT '商品数字编号';
ALTER TABLE `temp_trade` ADD COLUMN `PCC_AF` INT NULL COMMENT '天猫点券卡实付款金额';
ALTER TABLE `temp_trade` ADD COLUMN `PIC_PATH` VARCHAR(200) NULL COMMENT '商品图片绝对路径';
ALTER TABLE `temp_trade` ADD COLUMN `POST_FEE` DECIMAL(10,2) NULL COMMENT '邮费';
ALTER TABLE `temp_trade` ADD COLUMN `PRICE` DECIMAL(10,2) NULL COMMENT '商品价格';
ALTER TABLE `temp_trade` ADD COLUMN `REAL_POINT_FEE` INT NULL COMMENT '买家实际使用积分';
ALTER TABLE `temp_trade` ADD COLUMN `SELLER_ALIPAY_NO` VARCHAR(200) NULL COMMENT '卖家支付宝账号';
ALTER TABLE `temp_trade` ADD COLUMN `SELLER_CAN_RATE` VARCHAR(10) NULL COMMENT '卖家是否可以对订单进行评价';
ALTER TABLE `temp_trade` ADD COLUMN `SELLER_COD_FEE` DECIMAL(10,2) NULL COMMENT '卖家货到付款服务费';
ALTER TABLE `temp_trade` ADD COLUMN `SELLER_EMAIL` VARCHAR(200) NULL COMMENT '卖家邮件地址';
ALTER TABLE `temp_trade` ADD COLUMN `SELLER_FLAG` VARCHAR(200) NULL COMMENT '卖家备注旗帜';
ALTER TABLE `temp_trade` ADD COLUMN `SELLER_MOBILE` VARCHAR(200) NULL COMMENT '卖家手机';
ALTER TABLE `temp_trade` ADD COLUMN `SELLER_NAME` VARCHAR(200) NULL COMMENT '卖家姓名';
ALTER TABLE `temp_trade` ADD COLUMN `SELLER_PHONE` VARCHAR(200) NULL COMMENT '卖家电话';
ALTER TABLE `temp_trade` ADD COLUMN `SELLER_RATE` VARCHAR(200) NULL COMMENT '卖家是否已评价';
ALTER TABLE `temp_trade` ADD COLUMN `SNAPSHOT_URL` VARCHAR(200) NULL COMMENT '交易快照地址';
ALTER TABLE `temp_trade` ADD COLUMN `STEP_PAID_FEE` DECIMAL(10,2) NULL COMMENT '分阶段付款的已付金额（万人团订单已付金额）';
ALTER TABLE `temp_trade` ADD COLUMN `STEP_TRADE_STATUS` VARCHAR(200) NULL COMMENT '分阶段付款的订单状态';
ALTER TABLE `temp_trade` ADD COLUMN `TITLE` VARCHAR(200) NULL COMMENT '交易标题';
ALTER TABLE `temp_trade` ADD COLUMN `TRADE_FROM` VARCHAR(200) NULL COMMENT '交易内部来源';
ALTER TABLE `temp_trade` ADD COLUMN `TYPE` VARCHAR(200) NULL COMMENT '交易类型列表';
ALTER TABLE `temp_trade` ADD COLUMN `EST_CON_TIME` TIMESTAMP NULL COMMENT '商家的预计发货时间';
ALTER TABLE `temp_trade` ADD COLUMN `INVOICE_KIND` VARCHAR(10) NULL COMMENT '发票类型';
ALTER TABLE `temp_trade` ADD COLUMN `RECEIVER_COUNTRY` VARCHAR(200) NULL COMMENT '收货人国籍';
ALTER TABLE `temp_trade` ADD COLUMN `RECEIVER_TOWN` VARCHAR(200) NULL COMMENT '收货人街道地址';
ALTER TABLE `temp_trade` ADD COLUMN `ORDER_TAX_FEE` DECIMAL(10,2) NULL COMMENT '天猫国际官网直供主订单关税税费';
ALTER TABLE `temp_trade` ADD COLUMN `BUYER_MESSAGE` VARCHAR(500) NULL COMMENT '买家留言';
ALTER TABLE `temp_trade` ADD COLUMN `BUYER_MEMO` VARCHAR(500) NULL COMMENT '买家备注';
ALTER TABLE `temp_trade` ADD COLUMN `BUYER_FLAG` INT NULL COMMENT '买家备注旗帜';
ALTER TABLE `temp_trade` ADD COLUMN `INVOICE_TYPE` VARCHAR(200) NULL COMMENT '发票类型';
ALTER TABLE `temp_trade` ADD COLUMN `MARK_DESC` VARCHAR(200) NULL COMMENT '订单出现异常问题的时候，给予用户的描述,没有异常的时候，此值为空';
ALTER TABLE `temp_trade` ADD COLUMN `SHOP_CODE` VARCHAR(200) NULL COMMENT '线下自提门店编码';
ALTER TABLE `temp_trade` ADD COLUMN `TIMEOUT_ACTION_TIME` TIMESTAMP NULL COMMENT '超时到期时间';
ALTER TABLE `temp_trade` ADD COLUMN `PROMOTION` VARCHAR(200) NULL COMMENT '交易促销详细信息';
ALTER TABLE `temp_trade` ADD COLUMN `ET_SER_TIME` TIMESTAMP NULL COMMENT '天猫汽车服务预约时间';
ALTER TABLE `temp_trade` ADD COLUMN `ET_SHOP_NAME` VARCHAR(200) NULL COMMENT '电子凭证预约门店地址';
ALTER TABLE `temp_trade` ADD COLUMN `ET_VERIFIED_SHOP_NAME` VARCHAR(200) NULL COMMENT '电子凭证核销门店地址';
ALTER TABLE `temp_trade` ADD COLUMN `ET_PLATE_NUMBER` VARCHAR(200) NULL COMMENT '车牌号码';
ALTER TABLE `temp_trade` ADD COLUMN `PAID_COUPON_FEE` DECIMAL(10,2) NULL COMMENT '满返红包的金额';
ALTER TABLE `temp_trade` ADD COLUMN `SID` VARCHAR(200) NULL COMMENT '物流运单号';
ALTER TABLE `temp_trade` ADD COLUMN `BUYER_IP` VARCHAR(200) NULL COMMENT '买家下单的IP信息';
ALTER TABLE `temp_trade` ADD COLUMN `HAS_YFX` VARCHAR(200) NULL COMMENT '订单中是否包含运费险订单';
ALTER TABLE `temp_trade` ADD COLUMN `YFX_FEE` DECIMAL(10,2) NULL COMMENT '订单的运费险';
ALTER TABLE `temp_trade` ADD COLUMN `YFX_ID` VARCHAR(200) NULL COMMENT '运费险支付号';
ALTER TABLE `temp_trade` ADD COLUMN `YFX_TYPE` VARCHAR(200) NULL COMMENT '运费险类型';
ALTER TABLE `temp_trade` ADD COLUMN `ETICKET_EXT` VARCHAR(200) NULL COMMENT '电子凭证的垂直信息';
ALTER TABLE `temp_trade` ADD COLUMN `SEND_TIME` TIMESTAMP NULL COMMENT '订单将在此时间前发出，主要用于预售订单';
ALTER TABLE `temp_trade` ADD COLUMN `EXPRESS_AGENCY_FEE` DECIMAL(10,2) NULL COMMENT '快递代收款';
ALTER TABLE `temp_trade` ADD COLUMN `CAN_RATE` VARCHAR(10) NULL COMMENT '买家可以通过此字段查询是否当前交易可以评论';
ALTER TABLE `temp_trade` ADD COLUMN `ACOOKIE_ID` VARCHAR(200) NULL COMMENT 'ACOOKIE订单唯一ID';
ALTER TABLE `temp_trade` ADD COLUMN `TRADE_MEMO` VARCHAR(200) NULL COMMENT '交易备注';
ALTER TABLE `temp_trade` ADD COLUMN `TRADE_SOURCE` VARCHAR(200) NULL COMMENT '交易外部来源：OWNSHOP(商家官网)';
ALTER TABLE `temp_trade` ADD COLUMN `ARRIVE_INTERVAL` INT NULL COMMENT '物流到货时效，单位天';
ALTER TABLE `temp_trade` ADD COLUMN `ARRIVE_CUT_TIME` VARCHAR(200) NULL COMMENT '物流到货时效截单时间，格式 HH:MM';
ALTER TABLE `temp_trade` ADD COLUMN `CONSIGN_INTERVAL` INT NULL COMMENT '物流发货时效，单位小时';
ALTER TABLE `temp_trade` ADD COLUMN `O2O` VARCHAR(200) NULL COMMENT '导购宝=CRM';
ALTER TABLE `temp_trade` ADD COLUMN `O2O_GUIDE_ID` VARCHAR(200) NULL COMMENT '导购员ID';
ALTER TABLE `temp_trade` ADD COLUMN `O2O_SHOP_ID` VARCHAR(200) NULL COMMENT '导购员门店ID';
ALTER TABLE `temp_trade` ADD COLUMN `O2O_GUIDE_NAME` VARCHAR(200) NULL COMMENT '导购员名称';
ALTER TABLE `temp_trade` ADD COLUMN `O2O_SHOP_NAME` VARCHAR(200) NULL COMMENT '导购门店名称';
ALTER TABLE `temp_trade` ADD COLUMN `O2O_DELIVERY` VARCHAR(200) NULL COMMENT '导购宝提货方式';
ALTER TABLE `temp_trade` ADD COLUMN `ZERO_PURCHASE` VARCHAR(10) NULL COMMENT '';
ALTER TABLE `temp_trade` ADD COLUMN `O2O_OUT_TRADE_ID` VARCHAR(200) NULL COMMENT '外部订单号';
ALTER TABLE `temp_trade` ADD COLUMN `HK_EN_NAME` VARCHAR(200) NULL COMMENT '拼音名';
ALTER TABLE `temp_trade` ADD COLUMN `HK_FLIGHT_NO` VARCHAR(200) NULL COMMENT '航班号';
ALTER TABLE `temp_trade` ADD COLUMN `HK_CHINA_NAME` VARCHAR(200) NULL COMMENT '中文名';
ALTER TABLE `temp_trade` ADD COLUMN `HK_CARD_CODE` VARCHAR(200) NULL COMMENT '证件号码';
ALTER TABLE `temp_trade` ADD COLUMN `HK_CARD_TYPE` VARCHAR(200) NULL COMMENT '证件类型001代表港澳通行证类型、002代表入台证003代表护照';
ALTER TABLE `temp_trade` ADD COLUMN `HK_FLIGHT_DATE` VARCHAR(200) NULL COMMENT '航班飞行时间';
ALTER TABLE `temp_trade` ADD COLUMN `HK_GENDER` VARCHAR(200) NULL COMMENT '性别M: 男性，F: 女性';
ALTER TABLE `temp_trade` ADD COLUMN `HK_BIRTHDAY` VARCHAR(200) NULL COMMENT '出生日期';
ALTER TABLE `temp_trade` ADD COLUMN `HK_PICKUP` VARCHAR(200) NULL COMMENT '提货地点';
ALTER TABLE `temp_trade` ADD COLUMN `HK_PICKUP_ID` VARCHAR(200) NULL COMMENT '提货地点ID';
ALTER TABLE `temp_trade` ADD COLUMN `ETICKET_SERVICE_ADDR` VARCHAR(200) NULL COMMENT '天猫电子凭证家装';
ALTER TABLE `temp_trade` ADD COLUMN `IS_SH_SHIP` VARCHAR(10) NULL COMMENT '是否屏蔽发货';
ALTER TABLE `temp_trade` ADD COLUMN `O2O_SNATCH_STATUS` VARCHAR(10) NULL COMMENT '抢单状态';
ALTER TABLE `temp_trade` ADD COLUMN `MARKET` VARCHAR(200) NULL COMMENT '垂直市场';
ALTER TABLE `temp_trade` ADD COLUMN `ET_TYPE` VARCHAR(200) NULL COMMENT '电子凭证扫码购';
ALTER TABLE `temp_trade` ADD COLUMN `ET_SHOP_ID` VARCHAR(200) NULL COMMENT '扫码购关联门店';
ALTER TABLE `temp_trade` ADD COLUMN `OBS` VARCHAR(200) NULL COMMENT '门店预约自提订单标';


ALTER TABLE `temp_order` ADD COLUMN `ADJUST_FEE` DECIMAL(10,2) NULL COMMENT '手工调整金额';
ALTER TABLE `temp_order` ADD COLUMN `BUYER_RATE` VARCHAR(10) NULL COMMENT '买家是否已评价';
ALTER TABLE `temp_order` ADD COLUMN `CID` VARCHAR(100) NULL COMMENT '交易商品对应的类目ID';
ALTER TABLE `temp_order` ADD COLUMN `CONSIGN_TIME` TIMESTAMP NULL COMMENT '子订单发货时间';
ALTER TABLE `temp_order` ADD COLUMN `END_TIME` TIMESTAMP NULL COMMENT '子订单的交易结束时间';
ALTER TABLE `temp_order` ADD COLUMN `INVOICE_NO` VARCHAR(100) NULL COMMENT '子订单所在包裹的运单号';
ALTER TABLE `temp_order` ADD COLUMN `IS_OVERSOLD` VARCHAR(10) NULL COMMENT '是否超卖';
ALTER TABLE `temp_order` ADD COLUMN `IS_WWW` VARCHAR(10) NULL COMMENT '子订单是否是WWW订单';
ALTER TABLE `temp_order` ADD COLUMN `LOGISTICS_COMPANY` VARCHAR(100) NULL COMMENT '子订单发货的快递公司名称';
ALTER TABLE `temp_order` ADD COLUMN `NUM_IID` VARCHAR(100) NULL COMMENT '商品数字ID';
ALTER TABLE `temp_order` ADD COLUMN `OID` VARCHAR(100) NULL COMMENT '子订单编号';
ALTER TABLE `temp_order` ADD COLUMN `ORDER_FROM` VARCHAR(100) NULL COMMENT '子订单来源';
ALTER TABLE `temp_order` ADD COLUMN `PIC_PATH` VARCHAR(100) NULL COMMENT '商品图片的绝对路径';
ALTER TABLE `temp_order` ADD COLUMN `SELLER_RATE` VARCHAR(10) NULL COMMENT '卖家是否已评价';
ALTER TABLE `temp_order` ADD COLUMN `SELLER_TYPE` VARCHAR(10) NULL COMMENT '卖家类型，可选值为：B（商城商家），C（普通卖家）';
ALTER TABLE `temp_order` ADD COLUMN `SHIPPING_TYPE` VARCHAR(100) NULL COMMENT '子订单的运送方式';
ALTER TABLE `temp_order` ADD COLUMN `SKU_ID` VARCHAR(100) NULL COMMENT '商品的最小库存单位SKU的ID';
ALTER TABLE `temp_order` ADD COLUMN `SKU_PROPERTIES_NAME` VARCHAR(100) NULL COMMENT 'SKU的值';
ALTER TABLE `temp_order` ADD COLUMN `SNAPSHOT_URL` VARCHAR(100) NULL COMMENT '门店预约自提订单标';
ALTER TABLE `temp_order` ADD COLUMN `STATUS` VARCHAR(100) NULL COMMENT '订单状态';
ALTER TABLE `temp_order` ADD COLUMN `ITEM_MEAL_NAME` VARCHAR(50) NULL COMMENT '套餐的值';
ALTER TABLE `temp_order` ADD COLUMN `OUTER_IID` VARCHAR(100) NULL COMMENT '商家外部编码';
ALTER TABLE `temp_order` ADD COLUMN `TIMEOUT_ACTION_TIME` TIMESTAMP NULL COMMENT '订单超时到期时间';
ALTER TABLE `temp_order` ADD COLUMN `SUB_ORDER_TAX_FEE` VARCHAR(100) NULL COMMENT '天猫国际官网直供子订单关税税费';
ALTER TABLE `temp_order` ADD COLUMN `SUB_ORDER_TAX_RATE` VARCHAR(100) NULL COMMENT '天猫国际官网直供子订单关税税率';
ALTER TABLE `temp_order` ADD COLUMN `ITEM_MEAL_ID` VARCHAR(100) NULL COMMENT '套餐ID';
ALTER TABLE `temp_order` ADD COLUMN `OUTER_SKU_ID` VARCHAR(100) NULL COMMENT '外部网店自己定义的SKU编号';
ALTER TABLE `temp_order` ADD COLUMN `IS_SERVICE_ORDER` VARCHAR(10) NULL COMMENT '是否是服务订单';
ALTER TABLE `temp_order` ADD COLUMN `BIND_OID` VARCHAR(100) NULL COMMENT '捆绑的子订单号';
ALTER TABLE `temp_order` ADD COLUMN `IS_DAIXIAO` VARCHAR(10) NULL COMMENT '表示订单交易是否含有对应的代销采购单';
ALTER TABLE `temp_order` ADD COLUMN `TICKET_OUTER_ID` VARCHAR(100) NULL COMMENT '对应门票有效期的外部ID';
ALTER TABLE `temp_order` ADD COLUMN `TICKET_EXPDATE_KEY` VARCHAR(100) NULL COMMENT '门票有效期的KEY';
ALTER TABLE `temp_order` ADD COLUMN `TMSER_SPU_CODE` VARCHAR(100) NULL COMMENT '支持家装类物流的类型';
ALTER TABLE `temp_order` ADD COLUMN `ITEM_MEMO` VARCHAR(100) NULL COMMENT '商品备注';
ALTER TABLE `temp_order` ADD COLUMN `ET_SER_TIME` TIMESTAMP NULL COMMENT '天猫汽车服务预约时间';
ALTER TABLE `temp_order` ADD COLUMN `ET_SHOP_NAME` VARCHAR(100) NULL COMMENT '电子凭证预约门店地址';
ALTER TABLE `temp_order` ADD COLUMN `ET_VERIFIED_SHOP_NAME` VARCHAR(100) NULL COMMENT '电子凭证核销门店地址';
ALTER TABLE `temp_order` ADD COLUMN `ET_PLATE_NUMBER` VARCHAR(100) NULL COMMENT '车牌号码';
ALTER TABLE `temp_order` ADD COLUMN `ESTIMATE_CON_TIME` VARCHAR(100) NULL COMMENT '子订单预计发货时间';
ALTER TABLE `temp_order` ADD COLUMN `BIND_OIDS` VARCHAR(200) NULL COMMENT '支持返回绑定的多个子订单';
ALTER TABLE `temp_order` ADD COLUMN `ZHENGJI_STATUS` VARCHAR(10) NULL COMMENT '征集预售订单征集状态：1（征集中），2（征集成功），3（征集失败）';

